// Code generated by ent, DO NOT EDIT.

package bill

import (
	"clepsydra/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Bill {
	return predicate.Bill(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Bill {
	return predicate.Bill(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Bill {
	return predicate.Bill(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Bill {
	return predicate.Bill(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldName, v))
}

// Period applies equality check predicate on the "period" field. It's identical to PeriodEQ.
func Period(v string) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldPeriod, v))
}

// DailyRate applies equality check predicate on the "daily_rate" field. It's identical to DailyRateEQ.
func DailyRate(v int) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldDailyRate, v))
}

// BaseFee applies equality check predicate on the "base_fee" field. It's identical to BaseFeeEQ.
func BaseFee(v int) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldBaseFee, v))
}

// TotalHalfDays applies equality check predicate on the "total_half_days" field. It's identical to TotalHalfDaysEQ.
func TotalHalfDays(v int) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldTotalHalfDays, v))
}

// TotalAmount applies equality check predicate on the "total_amount" field. It's identical to TotalAmountEQ.
func TotalAmount(v int) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldTotalAmount, v))
}

// TotalOverride applies equality check predicate on the "total_override" field. It's identical to TotalOverrideEQ.
func TotalOverride(v bool) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldTotalOverride, v))
}

// ConfirmDeadline applies equality check predicate on the "confirm_deadline" field. It's identical to ConfirmDeadlineEQ.
func ConfirmDeadline(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldConfirmDeadline, v))
}

// ConfirmedAt applies equality check predicate on the "confirmed_at" field. It's identical to ConfirmedAtEQ.
func ConfirmedAt(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldConfirmedAt, v))
}

// ConfirmedBy applies equality check predicate on the "confirmed_by" field. It's identical to ConfirmedByEQ.
func ConfirmedBy(v int) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldConfirmedBy, v))
}

// ConfirmAuto applies equality check predicate on the "confirm_auto" field. It's identical to ConfirmAutoEQ.
func ConfirmAuto(v bool) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldConfirmAuto, v))
}

// PaidAt applies equality check predicate on the "paid_at" field. It's identical to PaidAtEQ.
func PaidAt(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldPaidAt, v))
}

// PaidBy applies equality check predicate on the "paid_by" field. It's identical to PaidByEQ.
func PaidBy(v int) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldPaidBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Bill {
	return predicate.Bill(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Bill {
	return predicate.Bill(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Bill {
	return predicate.Bill(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Bill {
	return predicate.Bill(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Bill {
	return predicate.Bill(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Bill {
	return predicate.Bill(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Bill {
	return predicate.Bill(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Bill {
	return predicate.Bill(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Bill {
	return predicate.Bill(sql.FieldContainsFold(FieldName, v))
}

// PeriodEQ applies the EQ predicate on the "period" field.
func PeriodEQ(v string) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldPeriod, v))
}

// PeriodNEQ applies the NEQ predicate on the "period" field.
func PeriodNEQ(v string) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldPeriod, v))
}

// PeriodIn applies the In predicate on the "period" field.
func PeriodIn(vs ...string) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldPeriod, vs...))
}

// PeriodNotIn applies the NotIn predicate on the "period" field.
func PeriodNotIn(vs ...string) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldPeriod, vs...))
}

// PeriodGT applies the GT predicate on the "period" field.
func PeriodGT(v string) predicate.Bill {
	return predicate.Bill(sql.FieldGT(FieldPeriod, v))
}

// PeriodGTE applies the GTE predicate on the "period" field.
func PeriodGTE(v string) predicate.Bill {
	return predicate.Bill(sql.FieldGTE(FieldPeriod, v))
}

// PeriodLT applies the LT predicate on the "period" field.
func PeriodLT(v string) predicate.Bill {
	return predicate.Bill(sql.FieldLT(FieldPeriod, v))
}

// PeriodLTE applies the LTE predicate on the "period" field.
func PeriodLTE(v string) predicate.Bill {
	return predicate.Bill(sql.FieldLTE(FieldPeriod, v))
}

// PeriodContains applies the Contains predicate on the "period" field.
func PeriodContains(v string) predicate.Bill {
	return predicate.Bill(sql.FieldContains(FieldPeriod, v))
}

// PeriodHasPrefix applies the HasPrefix predicate on the "period" field.
func PeriodHasPrefix(v string) predicate.Bill {
	return predicate.Bill(sql.FieldHasPrefix(FieldPeriod, v))
}

// PeriodHasSuffix applies the HasSuffix predicate on the "period" field.
func PeriodHasSuffix(v string) predicate.Bill {
	return predicate.Bill(sql.FieldHasSuffix(FieldPeriod, v))
}

// PeriodIsNil applies the IsNil predicate on the "period" field.
func PeriodIsNil() predicate.Bill {
	return predicate.Bill(sql.FieldIsNull(FieldPeriod))
}

// PeriodNotNil applies the NotNil predicate on the "period" field.
func PeriodNotNil() predicate.Bill {
	return predicate.Bill(sql.FieldNotNull(FieldPeriod))
}

// PeriodEqualFold applies the EqualFold predicate on the "period" field.
func PeriodEqualFold(v string) predicate.Bill {
	return predicate.Bill(sql.FieldEqualFold(FieldPeriod, v))
}

// PeriodContainsFold applies the ContainsFold predicate on the "period" field.
func PeriodContainsFold(v string) predicate.Bill {
	return predicate.Bill(sql.FieldContainsFold(FieldPeriod, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldStatus, vs...))
}

// DailyRateEQ applies the EQ predicate on the "daily_rate" field.
func DailyRateEQ(v int) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldDailyRate, v))
}

// DailyRateNEQ applies the NEQ predicate on the "daily_rate" field.
func DailyRateNEQ(v int) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldDailyRate, v))
}

// DailyRateIn applies the In predicate on the "daily_rate" field.
func DailyRateIn(vs ...int) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldDailyRate, vs...))
}

// DailyRateNotIn applies the NotIn predicate on the "daily_rate" field.
func DailyRateNotIn(vs ...int) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldDailyRate, vs...))
}

// DailyRateGT applies the GT predicate on the "daily_rate" field.
func DailyRateGT(v int) predicate.Bill {
	return predicate.Bill(sql.FieldGT(FieldDailyRate, v))
}

// DailyRateGTE applies the GTE predicate on the "daily_rate" field.
func DailyRateGTE(v int) predicate.Bill {
	return predicate.Bill(sql.FieldGTE(FieldDailyRate, v))
}

// DailyRateLT applies the LT predicate on the "daily_rate" field.
func DailyRateLT(v int) predicate.Bill {
	return predicate.Bill(sql.FieldLT(FieldDailyRate, v))
}

// DailyRateLTE applies the LTE predicate on the "daily_rate" field.
func DailyRateLTE(v int) predicate.Bill {
	return predicate.Bill(sql.FieldLTE(FieldDailyRate, v))
}

// BaseFeeEQ applies the EQ predicate on the "base_fee" field.
func BaseFeeEQ(v int) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldBaseFee, v))
}

// BaseFeeNEQ applies the NEQ predicate on the "base_fee" field.
func BaseFeeNEQ(v int) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldBaseFee, v))
}

// BaseFeeIn applies the In predicate on the "base_fee" field.
func BaseFeeIn(vs ...int) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldBaseFee, vs...))
}

// BaseFeeNotIn applies the NotIn predicate on the "base_fee" field.
func BaseFeeNotIn(vs ...int) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldBaseFee, vs...))
}

// BaseFeeGT applies the GT predicate on the "base_fee" field.
func BaseFeeGT(v int) predicate.Bill {
	return predicate.Bill(sql.FieldGT(FieldBaseFee, v))
}

// BaseFeeGTE applies the GTE predicate on the "base_fee" field.
func BaseFeeGTE(v int) predicate.Bill {
	return predicate.Bill(sql.FieldGTE(FieldBaseFee, v))
}

// BaseFeeLT applies the LT predicate on the "base_fee" field.
func BaseFeeLT(v int) predicate.Bill {
	return predicate.Bill(sql.FieldLT(FieldBaseFee, v))
}

// BaseFeeLTE applies the LTE predicate on the "base_fee" field.
func BaseFeeLTE(v int) predicate.Bill {
	return predicate.Bill(sql.FieldLTE(FieldBaseFee, v))
}

// TotalHalfDaysEQ applies the EQ predicate on the "total_half_days" field.
func TotalHalfDaysEQ(v int) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldTotalHalfDays, v))
}

// TotalHalfDaysNEQ applies the NEQ predicate on the "total_half_days" field.
func TotalHalfDaysNEQ(v int) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldTotalHalfDays, v))
}

// TotalHalfDaysIn applies the In predicate on the "total_half_days" field.
func TotalHalfDaysIn(vs ...int) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldTotalHalfDays, vs...))
}

// TotalHalfDaysNotIn applies the NotIn predicate on the "total_half_days" field.
func TotalHalfDaysNotIn(vs ...int) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldTotalHalfDays, vs...))
}

// TotalHalfDaysGT applies the GT predicate on the "total_half_days" field.
func TotalHalfDaysGT(v int) predicate.Bill {
	return predicate.Bill(sql.FieldGT(FieldTotalHalfDays, v))
}

// TotalHalfDaysGTE applies the GTE predicate on the "total_half_days" field.
func TotalHalfDaysGTE(v int) predicate.Bill {
	return predicate.Bill(sql.FieldGTE(FieldTotalHalfDays, v))
}

// TotalHalfDaysLT applies the LT predicate on the "total_half_days" field.
func TotalHalfDaysLT(v int) predicate.Bill {
	return predicate.Bill(sql.FieldLT(FieldTotalHalfDays, v))
}

// TotalHalfDaysLTE applies the LTE predicate on the "total_half_days" field.
func TotalHalfDaysLTE(v int) predicate.Bill {
	return predicate.Bill(sql.FieldLTE(FieldTotalHalfDays, v))
}

// TotalAmountEQ applies the EQ predicate on the "total_amount" field.
func TotalAmountEQ(v int) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldTotalAmount, v))
}

// TotalAmountNEQ applies the NEQ predicate on the "total_amount" field.
func TotalAmountNEQ(v int) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldTotalAmount, v))
}

// TotalAmountIn applies the In predicate on the "total_amount" field.
func TotalAmountIn(vs ...int) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldTotalAmount, vs...))
}

// TotalAmountNotIn applies the NotIn predicate on the "total_amount" field.
func TotalAmountNotIn(vs ...int) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldTotalAmount, vs...))
}

// TotalAmountGT applies the GT predicate on the "total_amount" field.
func TotalAmountGT(v int) predicate.Bill {
	return predicate.Bill(sql.FieldGT(FieldTotalAmount, v))
}

// TotalAmountGTE applies the GTE predicate on the "total_amount" field.
func TotalAmountGTE(v int) predicate.Bill {
	return predicate.Bill(sql.FieldGTE(FieldTotalAmount, v))
}

// TotalAmountLT applies the LT predicate on the "total_amount" field.
func TotalAmountLT(v int) predicate.Bill {
	return predicate.Bill(sql.FieldLT(FieldTotalAmount, v))
}

// TotalAmountLTE applies the LTE predicate on the "total_amount" field.
func TotalAmountLTE(v int) predicate.Bill {
	return predicate.Bill(sql.FieldLTE(FieldTotalAmount, v))
}

// TotalOverrideEQ applies the EQ predicate on the "total_override" field.
func TotalOverrideEQ(v bool) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldTotalOverride, v))
}

// TotalOverrideNEQ applies the NEQ predicate on the "total_override" field.
func TotalOverrideNEQ(v bool) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldTotalOverride, v))
}

// ConfirmDeadlineEQ applies the EQ predicate on the "confirm_deadline" field.
func ConfirmDeadlineEQ(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldConfirmDeadline, v))
}

// ConfirmDeadlineNEQ applies the NEQ predicate on the "confirm_deadline" field.
func ConfirmDeadlineNEQ(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldConfirmDeadline, v))
}

// ConfirmDeadlineIn applies the In predicate on the "confirm_deadline" field.
func ConfirmDeadlineIn(vs ...time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldConfirmDeadline, vs...))
}

// ConfirmDeadlineNotIn applies the NotIn predicate on the "confirm_deadline" field.
func ConfirmDeadlineNotIn(vs ...time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldConfirmDeadline, vs...))
}

// ConfirmDeadlineGT applies the GT predicate on the "confirm_deadline" field.
func ConfirmDeadlineGT(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldGT(FieldConfirmDeadline, v))
}

// ConfirmDeadlineGTE applies the GTE predicate on the "confirm_deadline" field.
func ConfirmDeadlineGTE(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldGTE(FieldConfirmDeadline, v))
}

// ConfirmDeadlineLT applies the LT predicate on the "confirm_deadline" field.
func ConfirmDeadlineLT(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldLT(FieldConfirmDeadline, v))
}

// ConfirmDeadlineLTE applies the LTE predicate on the "confirm_deadline" field.
func ConfirmDeadlineLTE(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldLTE(FieldConfirmDeadline, v))
}

// ConfirmDeadlineIsNil applies the IsNil predicate on the "confirm_deadline" field.
func ConfirmDeadlineIsNil() predicate.Bill {
	return predicate.Bill(sql.FieldIsNull(FieldConfirmDeadline))
}

// ConfirmDeadlineNotNil applies the NotNil predicate on the "confirm_deadline" field.
func ConfirmDeadlineNotNil() predicate.Bill {
	return predicate.Bill(sql.FieldNotNull(FieldConfirmDeadline))
}

// ConfirmedAtEQ applies the EQ predicate on the "confirmed_at" field.
func ConfirmedAtEQ(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldConfirmedAt, v))
}

// ConfirmedAtNEQ applies the NEQ predicate on the "confirmed_at" field.
func ConfirmedAtNEQ(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldConfirmedAt, v))
}

// ConfirmedAtIn applies the In predicate on the "confirmed_at" field.
func ConfirmedAtIn(vs ...time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldConfirmedAt, vs...))
}

// ConfirmedAtNotIn applies the NotIn predicate on the "confirmed_at" field.
func ConfirmedAtNotIn(vs ...time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldConfirmedAt, vs...))
}

// ConfirmedAtGT applies the GT predicate on the "confirmed_at" field.
func ConfirmedAtGT(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldGT(FieldConfirmedAt, v))
}

// ConfirmedAtGTE applies the GTE predicate on the "confirmed_at" field.
func ConfirmedAtGTE(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldGTE(FieldConfirmedAt, v))
}

// ConfirmedAtLT applies the LT predicate on the "confirmed_at" field.
func ConfirmedAtLT(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldLT(FieldConfirmedAt, v))
}

// ConfirmedAtLTE applies the LTE predicate on the "confirmed_at" field.
func ConfirmedAtLTE(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldLTE(FieldConfirmedAt, v))
}

// ConfirmedAtIsNil applies the IsNil predicate on the "confirmed_at" field.
func ConfirmedAtIsNil() predicate.Bill {
	return predicate.Bill(sql.FieldIsNull(FieldConfirmedAt))
}

// ConfirmedAtNotNil applies the NotNil predicate on the "confirmed_at" field.
func ConfirmedAtNotNil() predicate.Bill {
	return predicate.Bill(sql.FieldNotNull(FieldConfirmedAt))
}

// ConfirmedByEQ applies the EQ predicate on the "confirmed_by" field.
func ConfirmedByEQ(v int) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldConfirmedBy, v))
}

// ConfirmedByNEQ applies the NEQ predicate on the "confirmed_by" field.
func ConfirmedByNEQ(v int) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldConfirmedBy, v))
}

// ConfirmedByIn applies the In predicate on the "confirmed_by" field.
func ConfirmedByIn(vs ...int) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldConfirmedBy, vs...))
}

// ConfirmedByNotIn applies the NotIn predicate on the "confirmed_by" field.
func ConfirmedByNotIn(vs ...int) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldConfirmedBy, vs...))
}

// ConfirmedByGT applies the GT predicate on the "confirmed_by" field.
func ConfirmedByGT(v int) predicate.Bill {
	return predicate.Bill(sql.FieldGT(FieldConfirmedBy, v))
}

// ConfirmedByGTE applies the GTE predicate on the "confirmed_by" field.
func ConfirmedByGTE(v int) predicate.Bill {
	return predicate.Bill(sql.FieldGTE(FieldConfirmedBy, v))
}

// ConfirmedByLT applies the LT predicate on the "confirmed_by" field.
func ConfirmedByLT(v int) predicate.Bill {
	return predicate.Bill(sql.FieldLT(FieldConfirmedBy, v))
}

// ConfirmedByLTE applies the LTE predicate on the "confirmed_by" field.
func ConfirmedByLTE(v int) predicate.Bill {
	return predicate.Bill(sql.FieldLTE(FieldConfirmedBy, v))
}

// ConfirmedByIsNil applies the IsNil predicate on the "confirmed_by" field.
func ConfirmedByIsNil() predicate.Bill {
	return predicate.Bill(sql.FieldIsNull(FieldConfirmedBy))
}

// ConfirmedByNotNil applies the NotNil predicate on the "confirmed_by" field.
func ConfirmedByNotNil() predicate.Bill {
	return predicate.Bill(sql.FieldNotNull(FieldConfirmedBy))
}

// ConfirmAutoEQ applies the EQ predicate on the "confirm_auto" field.
func ConfirmAutoEQ(v bool) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldConfirmAuto, v))
}

// ConfirmAutoNEQ applies the NEQ predicate on the "confirm_auto" field.
func ConfirmAutoNEQ(v bool) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldConfirmAuto, v))
}

// PaidAtEQ applies the EQ predicate on the "paid_at" field.
func PaidAtEQ(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldPaidAt, v))
}

// PaidAtNEQ applies the NEQ predicate on the "paid_at" field.
func PaidAtNEQ(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldPaidAt, v))
}

// PaidAtIn applies the In predicate on the "paid_at" field.
func PaidAtIn(vs ...time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldPaidAt, vs...))
}

// PaidAtNotIn applies the NotIn predicate on the "paid_at" field.
func PaidAtNotIn(vs ...time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldPaidAt, vs...))
}

// PaidAtGT applies the GT predicate on the "paid_at" field.
func PaidAtGT(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldGT(FieldPaidAt, v))
}

// PaidAtGTE applies the GTE predicate on the "paid_at" field.
func PaidAtGTE(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldGTE(FieldPaidAt, v))
}

// PaidAtLT applies the LT predicate on the "paid_at" field.
func PaidAtLT(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldLT(FieldPaidAt, v))
}

// PaidAtLTE applies the LTE predicate on the "paid_at" field.
func PaidAtLTE(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldLTE(FieldPaidAt, v))
}

// PaidAtIsNil applies the IsNil predicate on the "paid_at" field.
func PaidAtIsNil() predicate.Bill {
	return predicate.Bill(sql.FieldIsNull(FieldPaidAt))
}

// PaidAtNotNil applies the NotNil predicate on the "paid_at" field.
func PaidAtNotNil() predicate.Bill {
	return predicate.Bill(sql.FieldNotNull(FieldPaidAt))
}

// PaidByEQ applies the EQ predicate on the "paid_by" field.
func PaidByEQ(v int) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldPaidBy, v))
}

// PaidByNEQ applies the NEQ predicate on the "paid_by" field.
func PaidByNEQ(v int) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldPaidBy, v))
}

// PaidByIn applies the In predicate on the "paid_by" field.
func PaidByIn(vs ...int) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldPaidBy, vs...))
}

// PaidByNotIn applies the NotIn predicate on the "paid_by" field.
func PaidByNotIn(vs ...int) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldPaidBy, vs...))
}

// PaidByGT applies the GT predicate on the "paid_by" field.
func PaidByGT(v int) predicate.Bill {
	return predicate.Bill(sql.FieldGT(FieldPaidBy, v))
}

// PaidByGTE applies the GTE predicate on the "paid_by" field.
func PaidByGTE(v int) predicate.Bill {
	return predicate.Bill(sql.FieldGTE(FieldPaidBy, v))
}

// PaidByLT applies the LT predicate on the "paid_by" field.
func PaidByLT(v int) predicate.Bill {
	return predicate.Bill(sql.FieldLT(FieldPaidBy, v))
}

// PaidByLTE applies the LTE predicate on the "paid_by" field.
func PaidByLTE(v int) predicate.Bill {
	return predicate.Bill(sql.FieldLTE(FieldPaidBy, v))
}

// PaidByIsNil applies the IsNil predicate on the "paid_by" field.
func PaidByIsNil() predicate.Bill {
	return predicate.Bill(sql.FieldIsNull(FieldPaidBy))
}

// PaidByNotNil applies the NotNil predicate on the "paid_by" field.
func PaidByNotNil() predicate.Bill {
	return predicate.Bill(sql.FieldNotNull(FieldPaidBy))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Bill {
	return predicate.Bill(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasItems applies the HasEdge predicate on the "items" edge.
func HasItems() predicate.Bill {
	return predicate.Bill(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ItemsTable, ItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemsWith applies the HasEdge predicate on the "items" edge with a given conditions (other predicates).
func HasItemsWith(preds ...predicate.BillItem) predicate.Bill {
	return predicate.Bill(func(s *sql.Selector) {
		step := newItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Bill) predicate.Bill {
	return predicate.Bill(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Bill) predicate.Bill {
	return predicate.Bill(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Bill) predicate.Bill {
	return predicate.Bill(sql.NotPredicates(p))
}
