// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AuditLogsColumns holds the columns for the "audit_logs" table.
	AuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "actor_id", Type: field.TypeInt},
		{Name: "actor_name", Type: field.TypeString},
		{Name: "action", Type: field.TypeString},
		{Name: "target_type", Type: field.TypeString},
		{Name: "target_id", Type: field.TypeInt},
		{Name: "detail", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AuditLogsTable holds the schema information for the "audit_logs" table.
	AuditLogsTable = &schema.Table{
		Name:       "audit_logs",
		Columns:    AuditLogsColumns,
		PrimaryKey: []*schema.Column{AuditLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "auditlog_target_type_target_id",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[4], AuditLogsColumns[5]},
			},
		},
	}
	// BillsColumns holds the columns for the "bills" table.
	BillsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "period", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"draft", "pending", "confirmed"}, Default: "draft"},
		{Name: "daily_rate", Type: field.TypeInt},
		{Name: "base_fee", Type: field.TypeInt},
		{Name: "total_half_days", Type: field.TypeInt},
		{Name: "total_amount", Type: field.TypeInt},
		{Name: "shared_at", Type: field.TypeTime, Nullable: true},
		{Name: "confirm_deadline", Type: field.TypeTime, Nullable: true},
		{Name: "confirmed_at", Type: field.TypeTime, Nullable: true},
		{Name: "confirmed_by", Type: field.TypeInt, Nullable: true},
		{Name: "confirm_auto", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// BillsTable holds the schema information for the "bills" table.
	BillsTable = &schema.Table{
		Name:       "bills",
		Columns:    BillsColumns,
		PrimaryKey: []*schema.Column{BillsColumns[0]},
	}
	// BillItemsColumns holds the columns for the "bill_items" table.
	BillItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "demand_id", Type: field.TypeInt},
		{Name: "demand_title", Type: field.TypeString},
		{Name: "demand_status", Type: field.TypeString},
		{Name: "half_days", Type: field.TypeInt},
		{Name: "amount", Type: field.TypeInt},
		{Name: "billable", Type: field.TypeBool},
		{Name: "waived", Type: field.TypeBool, Default: false},
		{Name: "planned_start_date", Type: field.TypeTime, Nullable: true},
		{Name: "note", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "bill_items", Type: field.TypeInt},
	}
	// BillItemsTable holds the schema information for the "bill_items" table.
	BillItemsTable = &schema.Table{
		Name:       "bill_items",
		Columns:    BillItemsColumns,
		PrimaryKey: []*schema.Column{BillItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "bill_items_bills_items",
				Columns:    []*schema.Column{BillItemsColumns[11]},
				RefColumns: []*schema.Column{BillsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// DemandsColumns holds the columns for the "demands" table.
	DemandsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "estimated_half_days", Type: field.TypeInt},
		{Name: "estimate_confirmed_at", Type: field.TypeTime, Nullable: true},
		{Name: "estimate_confirmed_by", Type: field.TypeInt, Nullable: true},
		{Name: "planned_start_date", Type: field.TypeTime, Nullable: true},
		{Name: "actual_start_date", Type: field.TypeTime, Nullable: true},
		{Name: "actual_end_date", Type: field.TypeTime, Nullable: true},
		{Name: "actual_half_days", Type: field.TypeInt, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"draft", "pending_estimate", "confirmed", "in_progress", "pending_acceptance", "accepted"}, Default: "draft"},
		{Name: "accept_deadline", Type: field.TypeTime, Nullable: true},
		{Name: "accepted_at", Type: field.TypeTime, Nullable: true},
		{Name: "accepted_by", Type: field.TypeInt, Nullable: true},
		{Name: "accept_auto", Type: field.TypeBool, Default: false},
		{Name: "accept_locked", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// DemandsTable holds the schema information for the "demands" table.
	DemandsTable = &schema.Table{
		Name:       "demands",
		Columns:    DemandsColumns,
		PrimaryKey: []*schema.Column{DemandsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "demand_status",
				Unique:  false,
				Columns: []*schema.Column{DemandsColumns[11]},
			},
			{
				Name:    "demand_actual_end_date",
				Unique:  false,
				Columns: []*schema.Column{DemandsColumns[9]},
			},
		},
	}
	// HolidaysColumns holds the columns for the "holidays" table.
	HolidaysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "date", Type: field.TypeString, Unique: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"holiday", "workday"}},
		{Name: "name", Type: field.TypeString, Nullable: true},
	}
	// HolidaysTable holds the schema information for the "holidays" table.
	HolidaysTable = &schema.Table{
		Name:       "holidays",
		Columns:    HolidaysColumns,
		PrimaryKey: []*schema.Column{HolidaysColumns[0]},
	}
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeString},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "client"}},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AuditLogsTable,
		BillsTable,
		BillItemsTable,
		DemandsTable,
		HolidaysTable,
		SettingsTable,
		UsersTable,
	}
)

func init() {
	BillItemsTable.ForeignKeys[0].RefTable = BillsTable
}
