// Code generated by ent, DO NOT EDIT.

package ent

import (
	"clepsydra/internal/ent/bill"
	"clepsydra/internal/ent/billitem"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// BillItem is the model entity for the BillItem schema.
type BillItem struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// DemandID holds the value of the "demand_id" field.
	DemandID int `json:"demand_id,omitempty"`
	// DemandTitle holds the value of the "demand_title" field.
	DemandTitle string `json:"demand_title,omitempty"`
	// DemandStatus holds the value of the "demand_status" field.
	DemandStatus string `json:"demand_status,omitempty"`
	// HalfDays holds the value of the "half_days" field.
	HalfDays int `json:"half_days,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount int `json:"amount,omitempty"`
	// Waived holds the value of the "waived" field.
	Waived bool `json:"waived,omitempty"`
	// PlannedStartDate holds the value of the "planned_start_date" field.
	PlannedStartDate *time.Time `json:"planned_start_date,omitempty"`
	// Note holds the value of the "note" field.
	Note string `json:"note,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BillItemQuery when eager-loading is set.
	Edges        BillItemEdges `json:"edges"`
	bill_items   *int
	selectValues sql.SelectValues
}

// BillItemEdges holds the relations/edges for other nodes in the graph.
type BillItemEdges struct {
	// Bill holds the value of the bill edge.
	Bill *Bill `json:"bill,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// BillOrErr returns the Bill value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BillItemEdges) BillOrErr() (*Bill, error) {
	if e.Bill != nil {
		return e.Bill, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: bill.Label}
	}
	return nil, &NotLoadedError{edge: "bill"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BillItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case billitem.FieldWaived:
			values[i] = new(sql.NullBool)
		case billitem.FieldID, billitem.FieldDemandID, billitem.FieldHalfDays, billitem.FieldAmount:
			values[i] = new(sql.NullInt64)
		case billitem.FieldDemandTitle, billitem.FieldDemandStatus, billitem.FieldNote:
			values[i] = new(sql.NullString)
		case billitem.FieldPlannedStartDate, billitem.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case billitem.ForeignKeys[0]: // bill_items
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BillItem fields.
func (_m *BillItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case billitem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case billitem.FieldDemandID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field demand_id", values[i])
			} else if value.Valid {
				_m.DemandID = int(value.Int64)
			}
		case billitem.FieldDemandTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field demand_title", values[i])
			} else if value.Valid {
				_m.DemandTitle = value.String
			}
		case billitem.FieldDemandStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field demand_status", values[i])
			} else if value.Valid {
				_m.DemandStatus = value.String
			}
		case billitem.FieldHalfDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field half_days", values[i])
			} else if value.Valid {
				_m.HalfDays = int(value.Int64)
			}
		case billitem.FieldAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = int(value.Int64)
			}
		case billitem.FieldWaived:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field waived", values[i])
			} else if value.Valid {
				_m.Waived = value.Bool
			}
		case billitem.FieldPlannedStartDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field planned_start_date", values[i])
			} else if value.Valid {
				_m.PlannedStartDate = new(time.Time)
				*_m.PlannedStartDate = value.Time
			}
		case billitem.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = value.String
			}
		case billitem.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case billitem.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field bill_items", value)
			} else if value.Valid {
				_m.bill_items = new(int)
				*_m.bill_items = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BillItem.
// This includes values selected through modifiers, order, etc.
func (_m *BillItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryBill queries the "bill" edge of the BillItem entity.
func (_m *BillItem) QueryBill() *BillQuery {
	return NewBillItemClient(_m.config).QueryBill(_m)
}

// Update returns a builder for updating this BillItem.
// Note that you need to call BillItem.Unwrap() before calling this method if this BillItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BillItem) Update() *BillItemUpdateOne {
	return NewBillItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BillItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BillItem) Unwrap() *BillItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BillItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BillItem) String() string {
	var builder strings.Builder
	builder.WriteString("BillItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("demand_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DemandID))
	builder.WriteString(", ")
	builder.WriteString("demand_title=")
	builder.WriteString(_m.DemandTitle)
	builder.WriteString(", ")
	builder.WriteString("demand_status=")
	builder.WriteString(_m.DemandStatus)
	builder.WriteString(", ")
	builder.WriteString("half_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.HalfDays))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("waived=")
	builder.WriteString(fmt.Sprintf("%v", _m.Waived))
	builder.WriteString(", ")
	if v := _m.PlannedStartDate; v != nil {
		builder.WriteString("planned_start_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("note=")
	builder.WriteString(_m.Note)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BillItems is a parsable slice of BillItem.
type BillItems []*BillItem
