// Code generated by ent, DO NOT EDIT.

package ent

import (
	"clepsydra/internal/ent/bill"
	"clepsydra/internal/ent/billitem"
	"clepsydra/internal/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BillItemQuery is the builder for querying BillItem entities.
type BillItemQuery struct {
	config
	ctx        *QueryContext
	order      []billitem.OrderOption
	inters     []Interceptor
	predicates []predicate.BillItem
	withBill   *BillQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BillItemQuery builder.
func (_q *BillItemQuery) Where(ps ...predicate.BillItem) *BillItemQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *BillItemQuery) Limit(limit int) *BillItemQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *BillItemQuery) Offset(offset int) *BillItemQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *BillItemQuery) Unique(unique bool) *BillItemQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *BillItemQuery) Order(o ...billitem.OrderOption) *BillItemQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryBill chains the current query on the "bill" edge.
func (_q *BillItemQuery) QueryBill() *BillQuery {
	query := (&BillClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(billitem.Table, billitem.FieldID, selector),
			sqlgraph.To(bill.Table, bill.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, billitem.BillTable, billitem.BillColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BillItem entity from the query.
// Returns a *NotFoundError when no BillItem was found.
func (_q *BillItemQuery) First(ctx context.Context) (*BillItem, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{billitem.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *BillItemQuery) FirstX(ctx context.Context) *BillItem {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BillItem ID from the query.
// Returns a *NotFoundError when no BillItem ID was found.
func (_q *BillItemQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{billitem.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *BillItemQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BillItem entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BillItem entity is found.
// Returns a *NotFoundError when no BillItem entities are found.
func (_q *BillItemQuery) Only(ctx context.Context) (*BillItem, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{billitem.Label}
	default:
		return nil, &NotSingularError{billitem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *BillItemQuery) OnlyX(ctx context.Context) *BillItem {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BillItem ID in the query.
// Returns a *NotSingularError when more than one BillItem ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *BillItemQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{billitem.Label}
	default:
		err = &NotSingularError{billitem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *BillItemQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BillItems.
func (_q *BillItemQuery) All(ctx context.Context) ([]*BillItem, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BillItem, *BillItemQuery]()
	return withInterceptors[[]*BillItem](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *BillItemQuery) AllX(ctx context.Context) []*BillItem {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BillItem IDs.
func (_q *BillItemQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(billitem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *BillItemQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *BillItemQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*BillItemQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *BillItemQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *BillItemQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *BillItemQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BillItemQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *BillItemQuery) Clone() *BillItemQuery {
	if _q == nil {
		return nil
	}
	return &BillItemQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]billitem.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.BillItem{}, _q.predicates...),
		withBill:   _q.withBill.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithBill tells the query-builder to eager-load the nodes that are connected to
// the "bill" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BillItemQuery) WithBill(opts ...func(*BillQuery)) *BillItemQuery {
	query := (&BillClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBill = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DemandID int `json:"demand_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BillItem.Query().
//		GroupBy(billitem.FieldDemandID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *BillItemQuery) GroupBy(field string, fields ...string) *BillItemGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BillItemGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = billitem.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DemandID int `json:"demand_id,omitempty"`
//	}
//
//	client.BillItem.Query().
//		Select(billitem.FieldDemandID).
//		Scan(ctx, &v)
func (_q *BillItemQuery) Select(fields ...string) *BillItemSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &BillItemSelect{BillItemQuery: _q}
	sbuild.label = billitem.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BillItemSelect configured with the given aggregations.
func (_q *BillItemQuery) Aggregate(fns ...AggregateFunc) *BillItemSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *BillItemQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !billitem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *BillItemQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BillItem, error) {
	var (
		nodes       = []*BillItem{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withBill != nil,
		}
	)
	if _q.withBill != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, billitem.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BillItem).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BillItem{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withBill; query != nil {
		if err := _q.loadBill(ctx, query, nodes, nil,
			func(n *BillItem, e *Bill) { n.Edges.Bill = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *BillItemQuery) loadBill(ctx context.Context, query *BillQuery, nodes []*BillItem, init func(*BillItem), assign func(*BillItem, *Bill)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*BillItem)
	for i := range nodes {
		if nodes[i].bill_items == nil {
			continue
		}
		fk := *nodes[i].bill_items
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(bill.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "bill_items" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *BillItemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *BillItemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(billitem.Table, billitem.Columns, sqlgraph.NewFieldSpec(billitem.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, billitem.FieldID)
		for i := range fields {
			if fields[i] != billitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *BillItemQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(billitem.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = billitem.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BillItemGroupBy is the group-by builder for BillItem entities.
type BillItemGroupBy struct {
	selector
	build *BillItemQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *BillItemGroupBy) Aggregate(fns ...AggregateFunc) *BillItemGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *BillItemGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BillItemQuery, *BillItemGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *BillItemGroupBy) sqlScan(ctx context.Context, root *BillItemQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BillItemSelect is the builder for selecting fields of BillItem entities.
type BillItemSelect struct {
	*BillItemQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *BillItemSelect) Aggregate(fns ...AggregateFunc) *BillItemSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *BillItemSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BillItemQuery, *BillItemSelect](ctx, _s.BillItemQuery, _s, _s.inters, v)
}

func (_s *BillItemSelect) sqlScan(ctx context.Context, root *BillItemQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
