// Code generated by ent, DO NOT EDIT.

package ent

import (
	"clepsydra/internal/ent/bill"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Bill is the model entity for the Bill schema.
type Bill struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Period holds the value of the "period" field.
	Period *string `json:"period,omitempty"`
	// Status holds the value of the "status" field.
	Status bill.Status `json:"status,omitempty"`
	// DailyRate holds the value of the "daily_rate" field.
	DailyRate int `json:"daily_rate,omitempty"`
	// BaseFee holds the value of the "base_fee" field.
	BaseFee int `json:"base_fee,omitempty"`
	// TotalHalfDays holds the value of the "total_half_days" field.
	TotalHalfDays int `json:"total_half_days,omitempty"`
	// TotalAmount holds the value of the "total_amount" field.
	TotalAmount int `json:"total_amount,omitempty"`
	// TotalOverride holds the value of the "total_override" field.
	TotalOverride bool `json:"total_override,omitempty"`
	// ConfirmDeadline holds the value of the "confirm_deadline" field.
	ConfirmDeadline *time.Time `json:"confirm_deadline,omitempty"`
	// ConfirmedAt holds the value of the "confirmed_at" field.
	ConfirmedAt *time.Time `json:"confirmed_at,omitempty"`
	// ConfirmedBy holds the value of the "confirmed_by" field.
	ConfirmedBy *int `json:"confirmed_by,omitempty"`
	// ConfirmAuto holds the value of the "confirm_auto" field.
	ConfirmAuto bool `json:"confirm_auto,omitempty"`
	// PaidAt holds the value of the "paid_at" field.
	PaidAt *time.Time `json:"paid_at,omitempty"`
	// PaidBy holds the value of the "paid_by" field.
	PaidBy *int `json:"paid_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BillQuery when eager-loading is set.
	Edges        BillEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BillEdges holds the relations/edges for other nodes in the graph.
type BillEdges struct {
	// Items holds the value of the items edge.
	Items []*BillItem `json:"items,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ItemsOrErr returns the Items value or an error if the edge
// was not loaded in eager-loading.
func (e BillEdges) ItemsOrErr() ([]*BillItem, error) {
	if e.loadedTypes[0] {
		return e.Items, nil
	}
	return nil, &NotLoadedError{edge: "items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Bill) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bill.FieldTotalOverride, bill.FieldConfirmAuto:
			values[i] = new(sql.NullBool)
		case bill.FieldID, bill.FieldDailyRate, bill.FieldBaseFee, bill.FieldTotalHalfDays, bill.FieldTotalAmount, bill.FieldConfirmedBy, bill.FieldPaidBy:
			values[i] = new(sql.NullInt64)
		case bill.FieldName, bill.FieldPeriod, bill.FieldStatus:
			values[i] = new(sql.NullString)
		case bill.FieldConfirmDeadline, bill.FieldConfirmedAt, bill.FieldPaidAt, bill.FieldCreatedAt, bill.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Bill fields.
func (_m *Bill) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bill.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case bill.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case bill.FieldPeriod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field period", values[i])
			} else if value.Valid {
				_m.Period = new(string)
				*_m.Period = value.String
			}
		case bill.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = bill.Status(value.String)
			}
		case bill.FieldDailyRate:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_rate", values[i])
			} else if value.Valid {
				_m.DailyRate = int(value.Int64)
			}
		case bill.FieldBaseFee:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field base_fee", values[i])
			} else if value.Valid {
				_m.BaseFee = int(value.Int64)
			}
		case bill.FieldTotalHalfDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_half_days", values[i])
			} else if value.Valid {
				_m.TotalHalfDays = int(value.Int64)
			}
		case bill.FieldTotalAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_amount", values[i])
			} else if value.Valid {
				_m.TotalAmount = int(value.Int64)
			}
		case bill.FieldTotalOverride:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field total_override", values[i])
			} else if value.Valid {
				_m.TotalOverride = value.Bool
			}
		case bill.FieldConfirmDeadline:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field confirm_deadline", values[i])
			} else if value.Valid {
				_m.ConfirmDeadline = new(time.Time)
				*_m.ConfirmDeadline = value.Time
			}
		case bill.FieldConfirmedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field confirmed_at", values[i])
			} else if value.Valid {
				_m.ConfirmedAt = new(time.Time)
				*_m.ConfirmedAt = value.Time
			}
		case bill.FieldConfirmedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field confirmed_by", values[i])
			} else if value.Valid {
				_m.ConfirmedBy = new(int)
				*_m.ConfirmedBy = int(value.Int64)
			}
		case bill.FieldConfirmAuto:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field confirm_auto", values[i])
			} else if value.Valid {
				_m.ConfirmAuto = value.Bool
			}
		case bill.FieldPaidAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field paid_at", values[i])
			} else if value.Valid {
				_m.PaidAt = new(time.Time)
				*_m.PaidAt = value.Time
			}
		case bill.FieldPaidBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field paid_by", values[i])
			} else if value.Valid {
				_m.PaidBy = new(int)
				*_m.PaidBy = int(value.Int64)
			}
		case bill.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case bill.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Bill.
// This includes values selected through modifiers, order, etc.
func (_m *Bill) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryItems queries the "items" edge of the Bill entity.
func (_m *Bill) QueryItems() *BillItemQuery {
	return NewBillClient(_m.config).QueryItems(_m)
}

// Update returns a builder for updating this Bill.
// Note that you need to call Bill.Unwrap() before calling this method if this Bill
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Bill) Update() *BillUpdateOne {
	return NewBillClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Bill entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Bill) Unwrap() *Bill {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Bill is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Bill) String() string {
	var builder strings.Builder
	builder.WriteString("Bill(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Period; v != nil {
		builder.WriteString("period=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("daily_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.DailyRate))
	builder.WriteString(", ")
	builder.WriteString("base_fee=")
	builder.WriteString(fmt.Sprintf("%v", _m.BaseFee))
	builder.WriteString(", ")
	builder.WriteString("total_half_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalHalfDays))
	builder.WriteString(", ")
	builder.WriteString("total_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalAmount))
	builder.WriteString(", ")
	builder.WriteString("total_override=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalOverride))
	builder.WriteString(", ")
	if v := _m.ConfirmDeadline; v != nil {
		builder.WriteString("confirm_deadline=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ConfirmedAt; v != nil {
		builder.WriteString("confirmed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ConfirmedBy; v != nil {
		builder.WriteString("confirmed_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("confirm_auto=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConfirmAuto))
	builder.WriteString(", ")
	if v := _m.PaidAt; v != nil {
		builder.WriteString("paid_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.PaidBy; v != nil {
		builder.WriteString("paid_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Bills is a parsable slice of Bill.
type Bills []*Bill
