// Code generated by ent, DO NOT EDIT.

package ent

import (
	"clepsydra/internal/ent/bill"
	"clepsydra/internal/ent/billitem"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BillCreate is the builder for creating a Bill entity.
type BillCreate struct {
	config
	mutation *BillMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *BillCreate) SetName(v string) *BillCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPeriod sets the "period" field.
func (_c *BillCreate) SetPeriod(v string) *BillCreate {
	_c.mutation.SetPeriod(v)
	return _c
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (_c *BillCreate) SetNillablePeriod(v *string) *BillCreate {
	if v != nil {
		_c.SetPeriod(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *BillCreate) SetStatus(v bill.Status) *BillCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *BillCreate) SetNillableStatus(v *bill.Status) *BillCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetDailyRate sets the "daily_rate" field.
func (_c *BillCreate) SetDailyRate(v int) *BillCreate {
	_c.mutation.SetDailyRate(v)
	return _c
}

// SetBaseFee sets the "base_fee" field.
func (_c *BillCreate) SetBaseFee(v int) *BillCreate {
	_c.mutation.SetBaseFee(v)
	return _c
}

// SetTotalHalfDays sets the "total_half_days" field.
func (_c *BillCreate) SetTotalHalfDays(v int) *BillCreate {
	_c.mutation.SetTotalHalfDays(v)
	return _c
}

// SetTotalAmount sets the "total_amount" field.
func (_c *BillCreate) SetTotalAmount(v int) *BillCreate {
	_c.mutation.SetTotalAmount(v)
	return _c
}

// SetTotalOverride sets the "total_override" field.
func (_c *BillCreate) SetTotalOverride(v bool) *BillCreate {
	_c.mutation.SetTotalOverride(v)
	return _c
}

// SetNillableTotalOverride sets the "total_override" field if the given value is not nil.
func (_c *BillCreate) SetNillableTotalOverride(v *bool) *BillCreate {
	if v != nil {
		_c.SetTotalOverride(*v)
	}
	return _c
}

// SetConfirmDeadline sets the "confirm_deadline" field.
func (_c *BillCreate) SetConfirmDeadline(v time.Time) *BillCreate {
	_c.mutation.SetConfirmDeadline(v)
	return _c
}

// SetNillableConfirmDeadline sets the "confirm_deadline" field if the given value is not nil.
func (_c *BillCreate) SetNillableConfirmDeadline(v *time.Time) *BillCreate {
	if v != nil {
		_c.SetConfirmDeadline(*v)
	}
	return _c
}

// SetConfirmedAt sets the "confirmed_at" field.
func (_c *BillCreate) SetConfirmedAt(v time.Time) *BillCreate {
	_c.mutation.SetConfirmedAt(v)
	return _c
}

// SetNillableConfirmedAt sets the "confirmed_at" field if the given value is not nil.
func (_c *BillCreate) SetNillableConfirmedAt(v *time.Time) *BillCreate {
	if v != nil {
		_c.SetConfirmedAt(*v)
	}
	return _c
}

// SetConfirmedBy sets the "confirmed_by" field.
func (_c *BillCreate) SetConfirmedBy(v int) *BillCreate {
	_c.mutation.SetConfirmedBy(v)
	return _c
}

// SetNillableConfirmedBy sets the "confirmed_by" field if the given value is not nil.
func (_c *BillCreate) SetNillableConfirmedBy(v *int) *BillCreate {
	if v != nil {
		_c.SetConfirmedBy(*v)
	}
	return _c
}

// SetConfirmAuto sets the "confirm_auto" field.
func (_c *BillCreate) SetConfirmAuto(v bool) *BillCreate {
	_c.mutation.SetConfirmAuto(v)
	return _c
}

// SetNillableConfirmAuto sets the "confirm_auto" field if the given value is not nil.
func (_c *BillCreate) SetNillableConfirmAuto(v *bool) *BillCreate {
	if v != nil {
		_c.SetConfirmAuto(*v)
	}
	return _c
}

// SetPaidAt sets the "paid_at" field.
func (_c *BillCreate) SetPaidAt(v time.Time) *BillCreate {
	_c.mutation.SetPaidAt(v)
	return _c
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_c *BillCreate) SetNillablePaidAt(v *time.Time) *BillCreate {
	if v != nil {
		_c.SetPaidAt(*v)
	}
	return _c
}

// SetPaidBy sets the "paid_by" field.
func (_c *BillCreate) SetPaidBy(v int) *BillCreate {
	_c.mutation.SetPaidBy(v)
	return _c
}

// SetNillablePaidBy sets the "paid_by" field if the given value is not nil.
func (_c *BillCreate) SetNillablePaidBy(v *int) *BillCreate {
	if v != nil {
		_c.SetPaidBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BillCreate) SetCreatedAt(v time.Time) *BillCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BillCreate) SetNillableCreatedAt(v *time.Time) *BillCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BillCreate) SetUpdatedAt(v time.Time) *BillCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BillCreate) SetNillableUpdatedAt(v *time.Time) *BillCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddItemIDs adds the "items" edge to the BillItem entity by IDs.
func (_c *BillCreate) AddItemIDs(ids ...int) *BillCreate {
	_c.mutation.AddItemIDs(ids...)
	return _c
}

// AddItems adds the "items" edges to the BillItem entity.
func (_c *BillCreate) AddItems(v ...*BillItem) *BillCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddItemIDs(ids...)
}

// Mutation returns the BillMutation object of the builder.
func (_c *BillCreate) Mutation() *BillMutation {
	return _c.mutation
}

// Save creates the Bill in the database.
func (_c *BillCreate) Save(ctx context.Context) (*Bill, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BillCreate) SaveX(ctx context.Context) *Bill {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BillCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BillCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BillCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := bill.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.TotalOverride(); !ok {
		v := bill.DefaultTotalOverride
		_c.mutation.SetTotalOverride(v)
	}
	if _, ok := _c.mutation.ConfirmAuto(); !ok {
		v := bill.DefaultConfirmAuto
		_c.mutation.SetConfirmAuto(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := bill.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := bill.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BillCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Bill.name"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Bill.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := bill.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Bill.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DailyRate(); !ok {
		return &ValidationError{Name: "daily_rate", err: errors.New(`ent: missing required field "Bill.daily_rate"`)}
	}
	if _, ok := _c.mutation.BaseFee(); !ok {
		return &ValidationError{Name: "base_fee", err: errors.New(`ent: missing required field "Bill.base_fee"`)}
	}
	if _, ok := _c.mutation.TotalHalfDays(); !ok {
		return &ValidationError{Name: "total_half_days", err: errors.New(`ent: missing required field "Bill.total_half_days"`)}
	}
	if _, ok := _c.mutation.TotalAmount(); !ok {
		return &ValidationError{Name: "total_amount", err: errors.New(`ent: missing required field "Bill.total_amount"`)}
	}
	if _, ok := _c.mutation.TotalOverride(); !ok {
		return &ValidationError{Name: "total_override", err: errors.New(`ent: missing required field "Bill.total_override"`)}
	}
	if _, ok := _c.mutation.ConfirmAuto(); !ok {
		return &ValidationError{Name: "confirm_auto", err: errors.New(`ent: missing required field "Bill.confirm_auto"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Bill.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Bill.updated_at"`)}
	}
	return nil
}

func (_c *BillCreate) sqlSave(ctx context.Context) (*Bill, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BillCreate) createSpec() (*Bill, *sqlgraph.CreateSpec) {
	var (
		_node = &Bill{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(bill.Table, sqlgraph.NewFieldSpec(bill.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(bill.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Period(); ok {
		_spec.SetField(bill.FieldPeriod, field.TypeString, value)
		_node.Period = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(bill.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.DailyRate(); ok {
		_spec.SetField(bill.FieldDailyRate, field.TypeInt, value)
		_node.DailyRate = value
	}
	if value, ok := _c.mutation.BaseFee(); ok {
		_spec.SetField(bill.FieldBaseFee, field.TypeInt, value)
		_node.BaseFee = value
	}
	if value, ok := _c.mutation.TotalHalfDays(); ok {
		_spec.SetField(bill.FieldTotalHalfDays, field.TypeInt, value)
		_node.TotalHalfDays = value
	}
	if value, ok := _c.mutation.TotalAmount(); ok {
		_spec.SetField(bill.FieldTotalAmount, field.TypeInt, value)
		_node.TotalAmount = value
	}
	if value, ok := _c.mutation.TotalOverride(); ok {
		_spec.SetField(bill.FieldTotalOverride, field.TypeBool, value)
		_node.TotalOverride = value
	}
	if value, ok := _c.mutation.ConfirmDeadline(); ok {
		_spec.SetField(bill.FieldConfirmDeadline, field.TypeTime, value)
		_node.ConfirmDeadline = &value
	}
	if value, ok := _c.mutation.ConfirmedAt(); ok {
		_spec.SetField(bill.FieldConfirmedAt, field.TypeTime, value)
		_node.ConfirmedAt = &value
	}
	if value, ok := _c.mutation.ConfirmedBy(); ok {
		_spec.SetField(bill.FieldConfirmedBy, field.TypeInt, value)
		_node.ConfirmedBy = &value
	}
	if value, ok := _c.mutation.ConfirmAuto(); ok {
		_spec.SetField(bill.FieldConfirmAuto, field.TypeBool, value)
		_node.ConfirmAuto = value
	}
	if value, ok := _c.mutation.PaidAt(); ok {
		_spec.SetField(bill.FieldPaidAt, field.TypeTime, value)
		_node.PaidAt = &value
	}
	if value, ok := _c.mutation.PaidBy(); ok {
		_spec.SetField(bill.FieldPaidBy, field.TypeInt, value)
		_node.PaidBy = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(bill.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(bill.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bill.ItemsTable,
			Columns: []string{bill.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(billitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BillCreateBulk is the builder for creating many Bill entities in bulk.
type BillCreateBulk struct {
	config
	err      error
	builders []*BillCreate
}

// Save creates the Bill entities in the database.
func (_c *BillCreateBulk) Save(ctx context.Context) ([]*Bill, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Bill, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BillMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BillCreateBulk) SaveX(ctx context.Context) []*Bill {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BillCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BillCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
