// Code generated by ent, DO NOT EDIT.

package ent

import (
	"clepsydra/internal/ent/bill"
	"clepsydra/internal/ent/billitem"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BillItemCreate is the builder for creating a BillItem entity.
type BillItemCreate struct {
	config
	mutation *BillItemMutation
	hooks    []Hook
}

// SetDemandID sets the "demand_id" field.
func (_c *BillItemCreate) SetDemandID(v int) *BillItemCreate {
	_c.mutation.SetDemandID(v)
	return _c
}

// SetDemandTitle sets the "demand_title" field.
func (_c *BillItemCreate) SetDemandTitle(v string) *BillItemCreate {
	_c.mutation.SetDemandTitle(v)
	return _c
}

// SetDemandStatus sets the "demand_status" field.
func (_c *BillItemCreate) SetDemandStatus(v string) *BillItemCreate {
	_c.mutation.SetDemandStatus(v)
	return _c
}

// SetHalfDays sets the "half_days" field.
func (_c *BillItemCreate) SetHalfDays(v int) *BillItemCreate {
	_c.mutation.SetHalfDays(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *BillItemCreate) SetAmount(v int) *BillItemCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetWaived sets the "waived" field.
func (_c *BillItemCreate) SetWaived(v bool) *BillItemCreate {
	_c.mutation.SetWaived(v)
	return _c
}

// SetNillableWaived sets the "waived" field if the given value is not nil.
func (_c *BillItemCreate) SetNillableWaived(v *bool) *BillItemCreate {
	if v != nil {
		_c.SetWaived(*v)
	}
	return _c
}

// SetPlannedStartDate sets the "planned_start_date" field.
func (_c *BillItemCreate) SetPlannedStartDate(v time.Time) *BillItemCreate {
	_c.mutation.SetPlannedStartDate(v)
	return _c
}

// SetNillablePlannedStartDate sets the "planned_start_date" field if the given value is not nil.
func (_c *BillItemCreate) SetNillablePlannedStartDate(v *time.Time) *BillItemCreate {
	if v != nil {
		_c.SetPlannedStartDate(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *BillItemCreate) SetNote(v string) *BillItemCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *BillItemCreate) SetNillableNote(v *string) *BillItemCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BillItemCreate) SetCreatedAt(v time.Time) *BillItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BillItemCreate) SetNillableCreatedAt(v *time.Time) *BillItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetBillID sets the "bill" edge to the Bill entity by ID.
func (_c *BillItemCreate) SetBillID(id int) *BillItemCreate {
	_c.mutation.SetBillID(id)
	return _c
}

// SetBill sets the "bill" edge to the Bill entity.
func (_c *BillItemCreate) SetBill(v *Bill) *BillItemCreate {
	return _c.SetBillID(v.ID)
}

// Mutation returns the BillItemMutation object of the builder.
func (_c *BillItemCreate) Mutation() *BillItemMutation {
	return _c.mutation
}

// Save creates the BillItem in the database.
func (_c *BillItemCreate) Save(ctx context.Context) (*BillItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BillItemCreate) SaveX(ctx context.Context) *BillItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BillItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BillItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BillItemCreate) defaults() {
	if _, ok := _c.mutation.Waived(); !ok {
		v := billitem.DefaultWaived
		_c.mutation.SetWaived(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := billitem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BillItemCreate) check() error {
	if _, ok := _c.mutation.DemandID(); !ok {
		return &ValidationError{Name: "demand_id", err: errors.New(`ent: missing required field "BillItem.demand_id"`)}
	}
	if _, ok := _c.mutation.DemandTitle(); !ok {
		return &ValidationError{Name: "demand_title", err: errors.New(`ent: missing required field "BillItem.demand_title"`)}
	}
	if _, ok := _c.mutation.DemandStatus(); !ok {
		return &ValidationError{Name: "demand_status", err: errors.New(`ent: missing required field "BillItem.demand_status"`)}
	}
	if _, ok := _c.mutation.HalfDays(); !ok {
		return &ValidationError{Name: "half_days", err: errors.New(`ent: missing required field "BillItem.half_days"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "BillItem.amount"`)}
	}
	if _, ok := _c.mutation.Waived(); !ok {
		return &ValidationError{Name: "waived", err: errors.New(`ent: missing required field "BillItem.waived"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BillItem.created_at"`)}
	}
	if len(_c.mutation.BillIDs()) == 0 {
		return &ValidationError{Name: "bill", err: errors.New(`ent: missing required edge "BillItem.bill"`)}
	}
	return nil
}

func (_c *BillItemCreate) sqlSave(ctx context.Context) (*BillItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BillItemCreate) createSpec() (*BillItem, *sqlgraph.CreateSpec) {
	var (
		_node = &BillItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(billitem.Table, sqlgraph.NewFieldSpec(billitem.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.DemandID(); ok {
		_spec.SetField(billitem.FieldDemandID, field.TypeInt, value)
		_node.DemandID = value
	}
	if value, ok := _c.mutation.DemandTitle(); ok {
		_spec.SetField(billitem.FieldDemandTitle, field.TypeString, value)
		_node.DemandTitle = value
	}
	if value, ok := _c.mutation.DemandStatus(); ok {
		_spec.SetField(billitem.FieldDemandStatus, field.TypeString, value)
		_node.DemandStatus = value
	}
	if value, ok := _c.mutation.HalfDays(); ok {
		_spec.SetField(billitem.FieldHalfDays, field.TypeInt, value)
		_node.HalfDays = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(billitem.FieldAmount, field.TypeInt, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Waived(); ok {
		_spec.SetField(billitem.FieldWaived, field.TypeBool, value)
		_node.Waived = value
	}
	if value, ok := _c.mutation.PlannedStartDate(); ok {
		_spec.SetField(billitem.FieldPlannedStartDate, field.TypeTime, value)
		_node.PlannedStartDate = &value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(billitem.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(billitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.BillIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   billitem.BillTable,
			Columns: []string{billitem.BillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.bill_items = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BillItemCreateBulk is the builder for creating many BillItem entities in bulk.
type BillItemCreateBulk struct {
	config
	err      error
	builders []*BillItemCreate
}

// Save creates the BillItem entities in the database.
func (_c *BillItemCreateBulk) Save(ctx context.Context) ([]*BillItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BillItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BillItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BillItemCreateBulk) SaveX(ctx context.Context) []*BillItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BillItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BillItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
