// Code generated by ent, DO NOT EDIT.

package ent

import (
	"clepsydra/internal/ent/bill"
	"clepsydra/internal/ent/billitem"
	"clepsydra/internal/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BillItemUpdate is the builder for updating BillItem entities.
type BillItemUpdate struct {
	config
	hooks    []Hook
	mutation *BillItemMutation
}

// Where appends a list predicates to the BillItemUpdate builder.
func (_u *BillItemUpdate) Where(ps ...predicate.BillItem) *BillItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDemandID sets the "demand_id" field.
func (_u *BillItemUpdate) SetDemandID(v int) *BillItemUpdate {
	_u.mutation.ResetDemandID()
	_u.mutation.SetDemandID(v)
	return _u
}

// SetNillableDemandID sets the "demand_id" field if the given value is not nil.
func (_u *BillItemUpdate) SetNillableDemandID(v *int) *BillItemUpdate {
	if v != nil {
		_u.SetDemandID(*v)
	}
	return _u
}

// AddDemandID adds value to the "demand_id" field.
func (_u *BillItemUpdate) AddDemandID(v int) *BillItemUpdate {
	_u.mutation.AddDemandID(v)
	return _u
}

// SetDemandTitle sets the "demand_title" field.
func (_u *BillItemUpdate) SetDemandTitle(v string) *BillItemUpdate {
	_u.mutation.SetDemandTitle(v)
	return _u
}

// SetNillableDemandTitle sets the "demand_title" field if the given value is not nil.
func (_u *BillItemUpdate) SetNillableDemandTitle(v *string) *BillItemUpdate {
	if v != nil {
		_u.SetDemandTitle(*v)
	}
	return _u
}

// SetDemandStatus sets the "demand_status" field.
func (_u *BillItemUpdate) SetDemandStatus(v string) *BillItemUpdate {
	_u.mutation.SetDemandStatus(v)
	return _u
}

// SetNillableDemandStatus sets the "demand_status" field if the given value is not nil.
func (_u *BillItemUpdate) SetNillableDemandStatus(v *string) *BillItemUpdate {
	if v != nil {
		_u.SetDemandStatus(*v)
	}
	return _u
}

// SetHalfDays sets the "half_days" field.
func (_u *BillItemUpdate) SetHalfDays(v int) *BillItemUpdate {
	_u.mutation.ResetHalfDays()
	_u.mutation.SetHalfDays(v)
	return _u
}

// SetNillableHalfDays sets the "half_days" field if the given value is not nil.
func (_u *BillItemUpdate) SetNillableHalfDays(v *int) *BillItemUpdate {
	if v != nil {
		_u.SetHalfDays(*v)
	}
	return _u
}

// AddHalfDays adds value to the "half_days" field.
func (_u *BillItemUpdate) AddHalfDays(v int) *BillItemUpdate {
	_u.mutation.AddHalfDays(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *BillItemUpdate) SetAmount(v int) *BillItemUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *BillItemUpdate) SetNillableAmount(v *int) *BillItemUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *BillItemUpdate) AddAmount(v int) *BillItemUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetBillable sets the "billable" field.
func (_u *BillItemUpdate) SetBillable(v bool) *BillItemUpdate {
	_u.mutation.SetBillable(v)
	return _u
}

// SetNillableBillable sets the "billable" field if the given value is not nil.
func (_u *BillItemUpdate) SetNillableBillable(v *bool) *BillItemUpdate {
	if v != nil {
		_u.SetBillable(*v)
	}
	return _u
}

// SetWaived sets the "waived" field.
func (_u *BillItemUpdate) SetWaived(v bool) *BillItemUpdate {
	_u.mutation.SetWaived(v)
	return _u
}

// SetNillableWaived sets the "waived" field if the given value is not nil.
func (_u *BillItemUpdate) SetNillableWaived(v *bool) *BillItemUpdate {
	if v != nil {
		_u.SetWaived(*v)
	}
	return _u
}

// SetPlannedStartDate sets the "planned_start_date" field.
func (_u *BillItemUpdate) SetPlannedStartDate(v time.Time) *BillItemUpdate {
	_u.mutation.SetPlannedStartDate(v)
	return _u
}

// SetNillablePlannedStartDate sets the "planned_start_date" field if the given value is not nil.
func (_u *BillItemUpdate) SetNillablePlannedStartDate(v *time.Time) *BillItemUpdate {
	if v != nil {
		_u.SetPlannedStartDate(*v)
	}
	return _u
}

// ClearPlannedStartDate clears the value of the "planned_start_date" field.
func (_u *BillItemUpdate) ClearPlannedStartDate() *BillItemUpdate {
	_u.mutation.ClearPlannedStartDate()
	return _u
}

// SetNote sets the "note" field.
func (_u *BillItemUpdate) SetNote(v string) *BillItemUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *BillItemUpdate) SetNillableNote(v *string) *BillItemUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *BillItemUpdate) ClearNote() *BillItemUpdate {
	_u.mutation.ClearNote()
	return _u
}

// SetBillID sets the "bill" edge to the Bill entity by ID.
func (_u *BillItemUpdate) SetBillID(id int) *BillItemUpdate {
	_u.mutation.SetBillID(id)
	return _u
}

// SetBill sets the "bill" edge to the Bill entity.
func (_u *BillItemUpdate) SetBill(v *Bill) *BillItemUpdate {
	return _u.SetBillID(v.ID)
}

// Mutation returns the BillItemMutation object of the builder.
func (_u *BillItemUpdate) Mutation() *BillItemMutation {
	return _u.mutation
}

// ClearBill clears the "bill" edge to the Bill entity.
func (_u *BillItemUpdate) ClearBill() *BillItemUpdate {
	_u.mutation.ClearBill()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BillItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BillItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BillItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BillItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BillItemUpdate) check() error {
	if _u.mutation.BillCleared() && len(_u.mutation.BillIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BillItem.bill"`)
	}
	return nil
}

func (_u *BillItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(billitem.Table, billitem.Columns, sqlgraph.NewFieldSpec(billitem.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DemandID(); ok {
		_spec.SetField(billitem.FieldDemandID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDemandID(); ok {
		_spec.AddField(billitem.FieldDemandID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DemandTitle(); ok {
		_spec.SetField(billitem.FieldDemandTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.DemandStatus(); ok {
		_spec.SetField(billitem.FieldDemandStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.HalfDays(); ok {
		_spec.SetField(billitem.FieldHalfDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHalfDays(); ok {
		_spec.AddField(billitem.FieldHalfDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(billitem.FieldAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(billitem.FieldAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Billable(); ok {
		_spec.SetField(billitem.FieldBillable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Waived(); ok {
		_spec.SetField(billitem.FieldWaived, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PlannedStartDate(); ok {
		_spec.SetField(billitem.FieldPlannedStartDate, field.TypeTime, value)
	}
	if _u.mutation.PlannedStartDateCleared() {
		_spec.ClearField(billitem.FieldPlannedStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(billitem.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(billitem.FieldNote, field.TypeString)
	}
	if _u.mutation.BillCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   billitem.BillTable,
			Columns: []string{billitem.BillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bill.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BillIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   billitem.BillTable,
			Columns: []string{billitem.BillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{billitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BillItemUpdateOne is the builder for updating a single BillItem entity.
type BillItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BillItemMutation
}

// SetDemandID sets the "demand_id" field.
func (_u *BillItemUpdateOne) SetDemandID(v int) *BillItemUpdateOne {
	_u.mutation.ResetDemandID()
	_u.mutation.SetDemandID(v)
	return _u
}

// SetNillableDemandID sets the "demand_id" field if the given value is not nil.
func (_u *BillItemUpdateOne) SetNillableDemandID(v *int) *BillItemUpdateOne {
	if v != nil {
		_u.SetDemandID(*v)
	}
	return _u
}

// AddDemandID adds value to the "demand_id" field.
func (_u *BillItemUpdateOne) AddDemandID(v int) *BillItemUpdateOne {
	_u.mutation.AddDemandID(v)
	return _u
}

// SetDemandTitle sets the "demand_title" field.
func (_u *BillItemUpdateOne) SetDemandTitle(v string) *BillItemUpdateOne {
	_u.mutation.SetDemandTitle(v)
	return _u
}

// SetNillableDemandTitle sets the "demand_title" field if the given value is not nil.
func (_u *BillItemUpdateOne) SetNillableDemandTitle(v *string) *BillItemUpdateOne {
	if v != nil {
		_u.SetDemandTitle(*v)
	}
	return _u
}

// SetDemandStatus sets the "demand_status" field.
func (_u *BillItemUpdateOne) SetDemandStatus(v string) *BillItemUpdateOne {
	_u.mutation.SetDemandStatus(v)
	return _u
}

// SetNillableDemandStatus sets the "demand_status" field if the given value is not nil.
func (_u *BillItemUpdateOne) SetNillableDemandStatus(v *string) *BillItemUpdateOne {
	if v != nil {
		_u.SetDemandStatus(*v)
	}
	return _u
}

// SetHalfDays sets the "half_days" field.
func (_u *BillItemUpdateOne) SetHalfDays(v int) *BillItemUpdateOne {
	_u.mutation.ResetHalfDays()
	_u.mutation.SetHalfDays(v)
	return _u
}

// SetNillableHalfDays sets the "half_days" field if the given value is not nil.
func (_u *BillItemUpdateOne) SetNillableHalfDays(v *int) *BillItemUpdateOne {
	if v != nil {
		_u.SetHalfDays(*v)
	}
	return _u
}

// AddHalfDays adds value to the "half_days" field.
func (_u *BillItemUpdateOne) AddHalfDays(v int) *BillItemUpdateOne {
	_u.mutation.AddHalfDays(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *BillItemUpdateOne) SetAmount(v int) *BillItemUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *BillItemUpdateOne) SetNillableAmount(v *int) *BillItemUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *BillItemUpdateOne) AddAmount(v int) *BillItemUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetBillable sets the "billable" field.
func (_u *BillItemUpdateOne) SetBillable(v bool) *BillItemUpdateOne {
	_u.mutation.SetBillable(v)
	return _u
}

// SetNillableBillable sets the "billable" field if the given value is not nil.
func (_u *BillItemUpdateOne) SetNillableBillable(v *bool) *BillItemUpdateOne {
	if v != nil {
		_u.SetBillable(*v)
	}
	return _u
}

// SetWaived sets the "waived" field.
func (_u *BillItemUpdateOne) SetWaived(v bool) *BillItemUpdateOne {
	_u.mutation.SetWaived(v)
	return _u
}

// SetNillableWaived sets the "waived" field if the given value is not nil.
func (_u *BillItemUpdateOne) SetNillableWaived(v *bool) *BillItemUpdateOne {
	if v != nil {
		_u.SetWaived(*v)
	}
	return _u
}

// SetPlannedStartDate sets the "planned_start_date" field.
func (_u *BillItemUpdateOne) SetPlannedStartDate(v time.Time) *BillItemUpdateOne {
	_u.mutation.SetPlannedStartDate(v)
	return _u
}

// SetNillablePlannedStartDate sets the "planned_start_date" field if the given value is not nil.
func (_u *BillItemUpdateOne) SetNillablePlannedStartDate(v *time.Time) *BillItemUpdateOne {
	if v != nil {
		_u.SetPlannedStartDate(*v)
	}
	return _u
}

// ClearPlannedStartDate clears the value of the "planned_start_date" field.
func (_u *BillItemUpdateOne) ClearPlannedStartDate() *BillItemUpdateOne {
	_u.mutation.ClearPlannedStartDate()
	return _u
}

// SetNote sets the "note" field.
func (_u *BillItemUpdateOne) SetNote(v string) *BillItemUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *BillItemUpdateOne) SetNillableNote(v *string) *BillItemUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *BillItemUpdateOne) ClearNote() *BillItemUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// SetBillID sets the "bill" edge to the Bill entity by ID.
func (_u *BillItemUpdateOne) SetBillID(id int) *BillItemUpdateOne {
	_u.mutation.SetBillID(id)
	return _u
}

// SetBill sets the "bill" edge to the Bill entity.
func (_u *BillItemUpdateOne) SetBill(v *Bill) *BillItemUpdateOne {
	return _u.SetBillID(v.ID)
}

// Mutation returns the BillItemMutation object of the builder.
func (_u *BillItemUpdateOne) Mutation() *BillItemMutation {
	return _u.mutation
}

// ClearBill clears the "bill" edge to the Bill entity.
func (_u *BillItemUpdateOne) ClearBill() *BillItemUpdateOne {
	_u.mutation.ClearBill()
	return _u
}

// Where appends a list predicates to the BillItemUpdate builder.
func (_u *BillItemUpdateOne) Where(ps ...predicate.BillItem) *BillItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BillItemUpdateOne) Select(field string, fields ...string) *BillItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BillItem entity.
func (_u *BillItemUpdateOne) Save(ctx context.Context) (*BillItem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BillItemUpdateOne) SaveX(ctx context.Context) *BillItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BillItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BillItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BillItemUpdateOne) check() error {
	if _u.mutation.BillCleared() && len(_u.mutation.BillIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BillItem.bill"`)
	}
	return nil
}

func (_u *BillItemUpdateOne) sqlSave(ctx context.Context) (_node *BillItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(billitem.Table, billitem.Columns, sqlgraph.NewFieldSpec(billitem.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BillItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, billitem.FieldID)
		for _, f := range fields {
			if !billitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != billitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DemandID(); ok {
		_spec.SetField(billitem.FieldDemandID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDemandID(); ok {
		_spec.AddField(billitem.FieldDemandID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DemandTitle(); ok {
		_spec.SetField(billitem.FieldDemandTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.DemandStatus(); ok {
		_spec.SetField(billitem.FieldDemandStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.HalfDays(); ok {
		_spec.SetField(billitem.FieldHalfDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHalfDays(); ok {
		_spec.AddField(billitem.FieldHalfDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(billitem.FieldAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(billitem.FieldAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Billable(); ok {
		_spec.SetField(billitem.FieldBillable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Waived(); ok {
		_spec.SetField(billitem.FieldWaived, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PlannedStartDate(); ok {
		_spec.SetField(billitem.FieldPlannedStartDate, field.TypeTime, value)
	}
	if _u.mutation.PlannedStartDateCleared() {
		_spec.ClearField(billitem.FieldPlannedStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(billitem.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(billitem.FieldNote, field.TypeString)
	}
	if _u.mutation.BillCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   billitem.BillTable,
			Columns: []string{billitem.BillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bill.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BillIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   billitem.BillTable,
			Columns: []string{billitem.BillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BillItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{billitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
