// Code generated by ent, DO NOT EDIT.

package ent

import (
	"clepsydra/internal/ent/demand"
	"clepsydra/internal/ent/project"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DemandCreate is the builder for creating a Demand entity.
type DemandCreate struct {
	config
	mutation *DemandMutation
	hooks    []Hook
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *DemandCreate) SetDeletedAt(v time.Time) *DemandCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *DemandCreate) SetNillableDeletedAt(v *time.Time) *DemandCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *DemandCreate) SetTitle(v string) *DemandCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *DemandCreate) SetDescription(v string) *DemandCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *DemandCreate) SetNillableDescription(v *string) *DemandCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetEstimatedHalfDays sets the "estimated_half_days" field.
func (_c *DemandCreate) SetEstimatedHalfDays(v int) *DemandCreate {
	_c.mutation.SetEstimatedHalfDays(v)
	return _c
}

// SetEstimateConfirmedAt sets the "estimate_confirmed_at" field.
func (_c *DemandCreate) SetEstimateConfirmedAt(v time.Time) *DemandCreate {
	_c.mutation.SetEstimateConfirmedAt(v)
	return _c
}

// SetNillableEstimateConfirmedAt sets the "estimate_confirmed_at" field if the given value is not nil.
func (_c *DemandCreate) SetNillableEstimateConfirmedAt(v *time.Time) *DemandCreate {
	if v != nil {
		_c.SetEstimateConfirmedAt(*v)
	}
	return _c
}

// SetEstimateConfirmedBy sets the "estimate_confirmed_by" field.
func (_c *DemandCreate) SetEstimateConfirmedBy(v int) *DemandCreate {
	_c.mutation.SetEstimateConfirmedBy(v)
	return _c
}

// SetNillableEstimateConfirmedBy sets the "estimate_confirmed_by" field if the given value is not nil.
func (_c *DemandCreate) SetNillableEstimateConfirmedBy(v *int) *DemandCreate {
	if v != nil {
		_c.SetEstimateConfirmedBy(*v)
	}
	return _c
}

// SetPlannedStartDate sets the "planned_start_date" field.
func (_c *DemandCreate) SetPlannedStartDate(v time.Time) *DemandCreate {
	_c.mutation.SetPlannedStartDate(v)
	return _c
}

// SetNillablePlannedStartDate sets the "planned_start_date" field if the given value is not nil.
func (_c *DemandCreate) SetNillablePlannedStartDate(v *time.Time) *DemandCreate {
	if v != nil {
		_c.SetPlannedStartDate(*v)
	}
	return _c
}

// SetActualStartDate sets the "actual_start_date" field.
func (_c *DemandCreate) SetActualStartDate(v time.Time) *DemandCreate {
	_c.mutation.SetActualStartDate(v)
	return _c
}

// SetNillableActualStartDate sets the "actual_start_date" field if the given value is not nil.
func (_c *DemandCreate) SetNillableActualStartDate(v *time.Time) *DemandCreate {
	if v != nil {
		_c.SetActualStartDate(*v)
	}
	return _c
}

// SetActualEndDate sets the "actual_end_date" field.
func (_c *DemandCreate) SetActualEndDate(v time.Time) *DemandCreate {
	_c.mutation.SetActualEndDate(v)
	return _c
}

// SetNillableActualEndDate sets the "actual_end_date" field if the given value is not nil.
func (_c *DemandCreate) SetNillableActualEndDate(v *time.Time) *DemandCreate {
	if v != nil {
		_c.SetActualEndDate(*v)
	}
	return _c
}

// SetActualHalfDays sets the "actual_half_days" field.
func (_c *DemandCreate) SetActualHalfDays(v int) *DemandCreate {
	_c.mutation.SetActualHalfDays(v)
	return _c
}

// SetNillableActualHalfDays sets the "actual_half_days" field if the given value is not nil.
func (_c *DemandCreate) SetNillableActualHalfDays(v *int) *DemandCreate {
	if v != nil {
		_c.SetActualHalfDays(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *DemandCreate) SetStatus(v demand.Status) *DemandCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DemandCreate) SetNillableStatus(v *demand.Status) *DemandCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAcceptDeadline sets the "accept_deadline" field.
func (_c *DemandCreate) SetAcceptDeadline(v time.Time) *DemandCreate {
	_c.mutation.SetAcceptDeadline(v)
	return _c
}

// SetNillableAcceptDeadline sets the "accept_deadline" field if the given value is not nil.
func (_c *DemandCreate) SetNillableAcceptDeadline(v *time.Time) *DemandCreate {
	if v != nil {
		_c.SetAcceptDeadline(*v)
	}
	return _c
}

// SetAcceptedAt sets the "accepted_at" field.
func (_c *DemandCreate) SetAcceptedAt(v time.Time) *DemandCreate {
	_c.mutation.SetAcceptedAt(v)
	return _c
}

// SetNillableAcceptedAt sets the "accepted_at" field if the given value is not nil.
func (_c *DemandCreate) SetNillableAcceptedAt(v *time.Time) *DemandCreate {
	if v != nil {
		_c.SetAcceptedAt(*v)
	}
	return _c
}

// SetAcceptedBy sets the "accepted_by" field.
func (_c *DemandCreate) SetAcceptedBy(v int) *DemandCreate {
	_c.mutation.SetAcceptedBy(v)
	return _c
}

// SetNillableAcceptedBy sets the "accepted_by" field if the given value is not nil.
func (_c *DemandCreate) SetNillableAcceptedBy(v *int) *DemandCreate {
	if v != nil {
		_c.SetAcceptedBy(*v)
	}
	return _c
}

// SetAcceptAuto sets the "accept_auto" field.
func (_c *DemandCreate) SetAcceptAuto(v bool) *DemandCreate {
	_c.mutation.SetAcceptAuto(v)
	return _c
}

// SetNillableAcceptAuto sets the "accept_auto" field if the given value is not nil.
func (_c *DemandCreate) SetNillableAcceptAuto(v *bool) *DemandCreate {
	if v != nil {
		_c.SetAcceptAuto(*v)
	}
	return _c
}

// SetAcceptLocked sets the "accept_locked" field.
func (_c *DemandCreate) SetAcceptLocked(v bool) *DemandCreate {
	_c.mutation.SetAcceptLocked(v)
	return _c
}

// SetNillableAcceptLocked sets the "accept_locked" field if the given value is not nil.
func (_c *DemandCreate) SetNillableAcceptLocked(v *bool) *DemandCreate {
	if v != nil {
		_c.SetAcceptLocked(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DemandCreate) SetCreatedAt(v time.Time) *DemandCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DemandCreate) SetNillableCreatedAt(v *time.Time) *DemandCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DemandCreate) SetUpdatedAt(v time.Time) *DemandCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DemandCreate) SetNillableUpdatedAt(v *time.Time) *DemandCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddProjectIDs adds the "projects" edge to the Project entity by IDs.
func (_c *DemandCreate) AddProjectIDs(ids ...int) *DemandCreate {
	_c.mutation.AddProjectIDs(ids...)
	return _c
}

// AddProjects adds the "projects" edges to the Project entity.
func (_c *DemandCreate) AddProjects(v ...*Project) *DemandCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProjectIDs(ids...)
}

// Mutation returns the DemandMutation object of the builder.
func (_c *DemandCreate) Mutation() *DemandMutation {
	return _c.mutation
}

// Save creates the Demand in the database.
func (_c *DemandCreate) Save(ctx context.Context) (*Demand, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DemandCreate) SaveX(ctx context.Context) *Demand {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DemandCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DemandCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DemandCreate) defaults() error {
	if _, ok := _c.mutation.Status(); !ok {
		v := demand.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.AcceptAuto(); !ok {
		v := demand.DefaultAcceptAuto
		_c.mutation.SetAcceptAuto(v)
	}
	if _, ok := _c.mutation.AcceptLocked(); !ok {
		v := demand.DefaultAcceptLocked
		_c.mutation.SetAcceptLocked(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if demand.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized demand.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := demand.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if demand.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized demand.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := demand.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *DemandCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Demand.title"`)}
	}
	if _, ok := _c.mutation.EstimatedHalfDays(); !ok {
		return &ValidationError{Name: "estimated_half_days", err: errors.New(`ent: missing required field "Demand.estimated_half_days"`)}
	}
	if v, ok := _c.mutation.EstimatedHalfDays(); ok {
		if err := demand.EstimatedHalfDaysValidator(v); err != nil {
			return &ValidationError{Name: "estimated_half_days", err: fmt.Errorf(`ent: validator failed for field "Demand.estimated_half_days": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Demand.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := demand.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Demand.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AcceptAuto(); !ok {
		return &ValidationError{Name: "accept_auto", err: errors.New(`ent: missing required field "Demand.accept_auto"`)}
	}
	if _, ok := _c.mutation.AcceptLocked(); !ok {
		return &ValidationError{Name: "accept_locked", err: errors.New(`ent: missing required field "Demand.accept_locked"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Demand.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Demand.updated_at"`)}
	}
	return nil
}

func (_c *DemandCreate) sqlSave(ctx context.Context) (*Demand, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DemandCreate) createSpec() (*Demand, *sqlgraph.CreateSpec) {
	var (
		_node = &Demand{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(demand.Table, sqlgraph.NewFieldSpec(demand.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(demand.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(demand.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(demand.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.EstimatedHalfDays(); ok {
		_spec.SetField(demand.FieldEstimatedHalfDays, field.TypeInt, value)
		_node.EstimatedHalfDays = value
	}
	if value, ok := _c.mutation.EstimateConfirmedAt(); ok {
		_spec.SetField(demand.FieldEstimateConfirmedAt, field.TypeTime, value)
		_node.EstimateConfirmedAt = &value
	}
	if value, ok := _c.mutation.EstimateConfirmedBy(); ok {
		_spec.SetField(demand.FieldEstimateConfirmedBy, field.TypeInt, value)
		_node.EstimateConfirmedBy = &value
	}
	if value, ok := _c.mutation.PlannedStartDate(); ok {
		_spec.SetField(demand.FieldPlannedStartDate, field.TypeTime, value)
		_node.PlannedStartDate = &value
	}
	if value, ok := _c.mutation.ActualStartDate(); ok {
		_spec.SetField(demand.FieldActualStartDate, field.TypeTime, value)
		_node.ActualStartDate = &value
	}
	if value, ok := _c.mutation.ActualEndDate(); ok {
		_spec.SetField(demand.FieldActualEndDate, field.TypeTime, value)
		_node.ActualEndDate = &value
	}
	if value, ok := _c.mutation.ActualHalfDays(); ok {
		_spec.SetField(demand.FieldActualHalfDays, field.TypeInt, value)
		_node.ActualHalfDays = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(demand.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AcceptDeadline(); ok {
		_spec.SetField(demand.FieldAcceptDeadline, field.TypeTime, value)
		_node.AcceptDeadline = &value
	}
	if value, ok := _c.mutation.AcceptedAt(); ok {
		_spec.SetField(demand.FieldAcceptedAt, field.TypeTime, value)
		_node.AcceptedAt = &value
	}
	if value, ok := _c.mutation.AcceptedBy(); ok {
		_spec.SetField(demand.FieldAcceptedBy, field.TypeInt, value)
		_node.AcceptedBy = &value
	}
	if value, ok := _c.mutation.AcceptAuto(); ok {
		_spec.SetField(demand.FieldAcceptAuto, field.TypeBool, value)
		_node.AcceptAuto = value
	}
	if value, ok := _c.mutation.AcceptLocked(); ok {
		_spec.SetField(demand.FieldAcceptLocked, field.TypeBool, value)
		_node.AcceptLocked = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(demand.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(demand.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ProjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   demand.ProjectsTable,
			Columns: demand.ProjectsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DemandCreateBulk is the builder for creating many Demand entities in bulk.
type DemandCreateBulk struct {
	config
	err      error
	builders []*DemandCreate
}

// Save creates the Demand entities in the database.
func (_c *DemandCreateBulk) Save(ctx context.Context) ([]*Demand, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Demand, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DemandMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DemandCreateBulk) SaveX(ctx context.Context) []*Demand {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DemandCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DemandCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
