// Code generated by ent, DO NOT EDIT.

package ent

import (
	"clepsydra/internal/ent/demand"
	"clepsydra/internal/ent/predicate"
	"clepsydra/internal/ent/project"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DemandUpdate is the builder for updating Demand entities.
type DemandUpdate struct {
	config
	hooks    []Hook
	mutation *DemandMutation
}

// Where appends a list predicates to the DemandUpdate builder.
func (_u *DemandUpdate) Where(ps ...predicate.Demand) *DemandUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DemandUpdate) SetDeletedAt(v time.Time) *DemandUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DemandUpdate) SetNillableDeletedAt(v *time.Time) *DemandUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DemandUpdate) ClearDeletedAt() *DemandUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetTitle sets the "title" field.
func (_u *DemandUpdate) SetTitle(v string) *DemandUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *DemandUpdate) SetNillableTitle(v *string) *DemandUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *DemandUpdate) SetDescription(v string) *DemandUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DemandUpdate) SetNillableDescription(v *string) *DemandUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *DemandUpdate) ClearDescription() *DemandUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetEstimatedHalfDays sets the "estimated_half_days" field.
func (_u *DemandUpdate) SetEstimatedHalfDays(v int) *DemandUpdate {
	_u.mutation.ResetEstimatedHalfDays()
	_u.mutation.SetEstimatedHalfDays(v)
	return _u
}

// SetNillableEstimatedHalfDays sets the "estimated_half_days" field if the given value is not nil.
func (_u *DemandUpdate) SetNillableEstimatedHalfDays(v *int) *DemandUpdate {
	if v != nil {
		_u.SetEstimatedHalfDays(*v)
	}
	return _u
}

// AddEstimatedHalfDays adds value to the "estimated_half_days" field.
func (_u *DemandUpdate) AddEstimatedHalfDays(v int) *DemandUpdate {
	_u.mutation.AddEstimatedHalfDays(v)
	return _u
}

// SetEstimateConfirmedAt sets the "estimate_confirmed_at" field.
func (_u *DemandUpdate) SetEstimateConfirmedAt(v time.Time) *DemandUpdate {
	_u.mutation.SetEstimateConfirmedAt(v)
	return _u
}

// SetNillableEstimateConfirmedAt sets the "estimate_confirmed_at" field if the given value is not nil.
func (_u *DemandUpdate) SetNillableEstimateConfirmedAt(v *time.Time) *DemandUpdate {
	if v != nil {
		_u.SetEstimateConfirmedAt(*v)
	}
	return _u
}

// ClearEstimateConfirmedAt clears the value of the "estimate_confirmed_at" field.
func (_u *DemandUpdate) ClearEstimateConfirmedAt() *DemandUpdate {
	_u.mutation.ClearEstimateConfirmedAt()
	return _u
}

// SetEstimateConfirmedBy sets the "estimate_confirmed_by" field.
func (_u *DemandUpdate) SetEstimateConfirmedBy(v int) *DemandUpdate {
	_u.mutation.ResetEstimateConfirmedBy()
	_u.mutation.SetEstimateConfirmedBy(v)
	return _u
}

// SetNillableEstimateConfirmedBy sets the "estimate_confirmed_by" field if the given value is not nil.
func (_u *DemandUpdate) SetNillableEstimateConfirmedBy(v *int) *DemandUpdate {
	if v != nil {
		_u.SetEstimateConfirmedBy(*v)
	}
	return _u
}

// AddEstimateConfirmedBy adds value to the "estimate_confirmed_by" field.
func (_u *DemandUpdate) AddEstimateConfirmedBy(v int) *DemandUpdate {
	_u.mutation.AddEstimateConfirmedBy(v)
	return _u
}

// ClearEstimateConfirmedBy clears the value of the "estimate_confirmed_by" field.
func (_u *DemandUpdate) ClearEstimateConfirmedBy() *DemandUpdate {
	_u.mutation.ClearEstimateConfirmedBy()
	return _u
}

// SetPlannedStartDate sets the "planned_start_date" field.
func (_u *DemandUpdate) SetPlannedStartDate(v time.Time) *DemandUpdate {
	_u.mutation.SetPlannedStartDate(v)
	return _u
}

// SetNillablePlannedStartDate sets the "planned_start_date" field if the given value is not nil.
func (_u *DemandUpdate) SetNillablePlannedStartDate(v *time.Time) *DemandUpdate {
	if v != nil {
		_u.SetPlannedStartDate(*v)
	}
	return _u
}

// ClearPlannedStartDate clears the value of the "planned_start_date" field.
func (_u *DemandUpdate) ClearPlannedStartDate() *DemandUpdate {
	_u.mutation.ClearPlannedStartDate()
	return _u
}

// SetActualStartDate sets the "actual_start_date" field.
func (_u *DemandUpdate) SetActualStartDate(v time.Time) *DemandUpdate {
	_u.mutation.SetActualStartDate(v)
	return _u
}

// SetNillableActualStartDate sets the "actual_start_date" field if the given value is not nil.
func (_u *DemandUpdate) SetNillableActualStartDate(v *time.Time) *DemandUpdate {
	if v != nil {
		_u.SetActualStartDate(*v)
	}
	return _u
}

// ClearActualStartDate clears the value of the "actual_start_date" field.
func (_u *DemandUpdate) ClearActualStartDate() *DemandUpdate {
	_u.mutation.ClearActualStartDate()
	return _u
}

// SetActualEndDate sets the "actual_end_date" field.
func (_u *DemandUpdate) SetActualEndDate(v time.Time) *DemandUpdate {
	_u.mutation.SetActualEndDate(v)
	return _u
}

// SetNillableActualEndDate sets the "actual_end_date" field if the given value is not nil.
func (_u *DemandUpdate) SetNillableActualEndDate(v *time.Time) *DemandUpdate {
	if v != nil {
		_u.SetActualEndDate(*v)
	}
	return _u
}

// ClearActualEndDate clears the value of the "actual_end_date" field.
func (_u *DemandUpdate) ClearActualEndDate() *DemandUpdate {
	_u.mutation.ClearActualEndDate()
	return _u
}

// SetActualHalfDays sets the "actual_half_days" field.
func (_u *DemandUpdate) SetActualHalfDays(v int) *DemandUpdate {
	_u.mutation.ResetActualHalfDays()
	_u.mutation.SetActualHalfDays(v)
	return _u
}

// SetNillableActualHalfDays sets the "actual_half_days" field if the given value is not nil.
func (_u *DemandUpdate) SetNillableActualHalfDays(v *int) *DemandUpdate {
	if v != nil {
		_u.SetActualHalfDays(*v)
	}
	return _u
}

// AddActualHalfDays adds value to the "actual_half_days" field.
func (_u *DemandUpdate) AddActualHalfDays(v int) *DemandUpdate {
	_u.mutation.AddActualHalfDays(v)
	return _u
}

// ClearActualHalfDays clears the value of the "actual_half_days" field.
func (_u *DemandUpdate) ClearActualHalfDays() *DemandUpdate {
	_u.mutation.ClearActualHalfDays()
	return _u
}

// SetStatus sets the "status" field.
func (_u *DemandUpdate) SetStatus(v demand.Status) *DemandUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DemandUpdate) SetNillableStatus(v *demand.Status) *DemandUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAcceptDeadline sets the "accept_deadline" field.
func (_u *DemandUpdate) SetAcceptDeadline(v time.Time) *DemandUpdate {
	_u.mutation.SetAcceptDeadline(v)
	return _u
}

// SetNillableAcceptDeadline sets the "accept_deadline" field if the given value is not nil.
func (_u *DemandUpdate) SetNillableAcceptDeadline(v *time.Time) *DemandUpdate {
	if v != nil {
		_u.SetAcceptDeadline(*v)
	}
	return _u
}

// ClearAcceptDeadline clears the value of the "accept_deadline" field.
func (_u *DemandUpdate) ClearAcceptDeadline() *DemandUpdate {
	_u.mutation.ClearAcceptDeadline()
	return _u
}

// SetAcceptedAt sets the "accepted_at" field.
func (_u *DemandUpdate) SetAcceptedAt(v time.Time) *DemandUpdate {
	_u.mutation.SetAcceptedAt(v)
	return _u
}

// SetNillableAcceptedAt sets the "accepted_at" field if the given value is not nil.
func (_u *DemandUpdate) SetNillableAcceptedAt(v *time.Time) *DemandUpdate {
	if v != nil {
		_u.SetAcceptedAt(*v)
	}
	return _u
}

// ClearAcceptedAt clears the value of the "accepted_at" field.
func (_u *DemandUpdate) ClearAcceptedAt() *DemandUpdate {
	_u.mutation.ClearAcceptedAt()
	return _u
}

// SetAcceptedBy sets the "accepted_by" field.
func (_u *DemandUpdate) SetAcceptedBy(v int) *DemandUpdate {
	_u.mutation.ResetAcceptedBy()
	_u.mutation.SetAcceptedBy(v)
	return _u
}

// SetNillableAcceptedBy sets the "accepted_by" field if the given value is not nil.
func (_u *DemandUpdate) SetNillableAcceptedBy(v *int) *DemandUpdate {
	if v != nil {
		_u.SetAcceptedBy(*v)
	}
	return _u
}

// AddAcceptedBy adds value to the "accepted_by" field.
func (_u *DemandUpdate) AddAcceptedBy(v int) *DemandUpdate {
	_u.mutation.AddAcceptedBy(v)
	return _u
}

// ClearAcceptedBy clears the value of the "accepted_by" field.
func (_u *DemandUpdate) ClearAcceptedBy() *DemandUpdate {
	_u.mutation.ClearAcceptedBy()
	return _u
}

// SetAcceptAuto sets the "accept_auto" field.
func (_u *DemandUpdate) SetAcceptAuto(v bool) *DemandUpdate {
	_u.mutation.SetAcceptAuto(v)
	return _u
}

// SetNillableAcceptAuto sets the "accept_auto" field if the given value is not nil.
func (_u *DemandUpdate) SetNillableAcceptAuto(v *bool) *DemandUpdate {
	if v != nil {
		_u.SetAcceptAuto(*v)
	}
	return _u
}

// SetAcceptLocked sets the "accept_locked" field.
func (_u *DemandUpdate) SetAcceptLocked(v bool) *DemandUpdate {
	_u.mutation.SetAcceptLocked(v)
	return _u
}

// SetNillableAcceptLocked sets the "accept_locked" field if the given value is not nil.
func (_u *DemandUpdate) SetNillableAcceptLocked(v *bool) *DemandUpdate {
	if v != nil {
		_u.SetAcceptLocked(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DemandUpdate) SetUpdatedAt(v time.Time) *DemandUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddProjectIDs adds the "projects" edge to the Project entity by IDs.
func (_u *DemandUpdate) AddProjectIDs(ids ...int) *DemandUpdate {
	_u.mutation.AddProjectIDs(ids...)
	return _u
}

// AddProjects adds the "projects" edges to the Project entity.
func (_u *DemandUpdate) AddProjects(v ...*Project) *DemandUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProjectIDs(ids...)
}

// Mutation returns the DemandMutation object of the builder.
func (_u *DemandUpdate) Mutation() *DemandMutation {
	return _u.mutation
}

// ClearProjects clears all "projects" edges to the Project entity.
func (_u *DemandUpdate) ClearProjects() *DemandUpdate {
	_u.mutation.ClearProjects()
	return _u
}

// RemoveProjectIDs removes the "projects" edge to Project entities by IDs.
func (_u *DemandUpdate) RemoveProjectIDs(ids ...int) *DemandUpdate {
	_u.mutation.RemoveProjectIDs(ids...)
	return _u
}

// RemoveProjects removes "projects" edges to Project entities.
func (_u *DemandUpdate) RemoveProjects(v ...*Project) *DemandUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProjectIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DemandUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DemandUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DemandUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DemandUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DemandUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if demand.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized demand.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := demand.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *DemandUpdate) check() error {
	if v, ok := _u.mutation.EstimatedHalfDays(); ok {
		if err := demand.EstimatedHalfDaysValidator(v); err != nil {
			return &ValidationError{Name: "estimated_half_days", err: fmt.Errorf(`ent: validator failed for field "Demand.estimated_half_days": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := demand.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Demand.status": %w`, err)}
		}
	}
	return nil
}

func (_u *DemandUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(demand.Table, demand.Columns, sqlgraph.NewFieldSpec(demand.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(demand.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(demand.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(demand.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(demand.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(demand.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.EstimatedHalfDays(); ok {
		_spec.SetField(demand.FieldEstimatedHalfDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEstimatedHalfDays(); ok {
		_spec.AddField(demand.FieldEstimatedHalfDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EstimateConfirmedAt(); ok {
		_spec.SetField(demand.FieldEstimateConfirmedAt, field.TypeTime, value)
	}
	if _u.mutation.EstimateConfirmedAtCleared() {
		_spec.ClearField(demand.FieldEstimateConfirmedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EstimateConfirmedBy(); ok {
		_spec.SetField(demand.FieldEstimateConfirmedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEstimateConfirmedBy(); ok {
		_spec.AddField(demand.FieldEstimateConfirmedBy, field.TypeInt, value)
	}
	if _u.mutation.EstimateConfirmedByCleared() {
		_spec.ClearField(demand.FieldEstimateConfirmedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.PlannedStartDate(); ok {
		_spec.SetField(demand.FieldPlannedStartDate, field.TypeTime, value)
	}
	if _u.mutation.PlannedStartDateCleared() {
		_spec.ClearField(demand.FieldPlannedStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.ActualStartDate(); ok {
		_spec.SetField(demand.FieldActualStartDate, field.TypeTime, value)
	}
	if _u.mutation.ActualStartDateCleared() {
		_spec.ClearField(demand.FieldActualStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.ActualEndDate(); ok {
		_spec.SetField(demand.FieldActualEndDate, field.TypeTime, value)
	}
	if _u.mutation.ActualEndDateCleared() {
		_spec.ClearField(demand.FieldActualEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.ActualHalfDays(); ok {
		_spec.SetField(demand.FieldActualHalfDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActualHalfDays(); ok {
		_spec.AddField(demand.FieldActualHalfDays, field.TypeInt, value)
	}
	if _u.mutation.ActualHalfDaysCleared() {
		_spec.ClearField(demand.FieldActualHalfDays, field.TypeInt)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(demand.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AcceptDeadline(); ok {
		_spec.SetField(demand.FieldAcceptDeadline, field.TypeTime, value)
	}
	if _u.mutation.AcceptDeadlineCleared() {
		_spec.ClearField(demand.FieldAcceptDeadline, field.TypeTime)
	}
	if value, ok := _u.mutation.AcceptedAt(); ok {
		_spec.SetField(demand.FieldAcceptedAt, field.TypeTime, value)
	}
	if _u.mutation.AcceptedAtCleared() {
		_spec.ClearField(demand.FieldAcceptedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AcceptedBy(); ok {
		_spec.SetField(demand.FieldAcceptedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAcceptedBy(); ok {
		_spec.AddField(demand.FieldAcceptedBy, field.TypeInt, value)
	}
	if _u.mutation.AcceptedByCleared() {
		_spec.ClearField(demand.FieldAcceptedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.AcceptAuto(); ok {
		_spec.SetField(demand.FieldAcceptAuto, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AcceptLocked(); ok {
		_spec.SetField(demand.FieldAcceptLocked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(demand.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   demand.ProjectsTable,
			Columns: demand.ProjectsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProjectsIDs(); len(nodes) > 0 && !_u.mutation.ProjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   demand.ProjectsTable,
			Columns: demand.ProjectsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   demand.ProjectsTable,
			Columns: demand.ProjectsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{demand.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DemandUpdateOne is the builder for updating a single Demand entity.
type DemandUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DemandMutation
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DemandUpdateOne) SetDeletedAt(v time.Time) *DemandUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DemandUpdateOne) SetNillableDeletedAt(v *time.Time) *DemandUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DemandUpdateOne) ClearDeletedAt() *DemandUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetTitle sets the "title" field.
func (_u *DemandUpdateOne) SetTitle(v string) *DemandUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *DemandUpdateOne) SetNillableTitle(v *string) *DemandUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *DemandUpdateOne) SetDescription(v string) *DemandUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DemandUpdateOne) SetNillableDescription(v *string) *DemandUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *DemandUpdateOne) ClearDescription() *DemandUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetEstimatedHalfDays sets the "estimated_half_days" field.
func (_u *DemandUpdateOne) SetEstimatedHalfDays(v int) *DemandUpdateOne {
	_u.mutation.ResetEstimatedHalfDays()
	_u.mutation.SetEstimatedHalfDays(v)
	return _u
}

// SetNillableEstimatedHalfDays sets the "estimated_half_days" field if the given value is not nil.
func (_u *DemandUpdateOne) SetNillableEstimatedHalfDays(v *int) *DemandUpdateOne {
	if v != nil {
		_u.SetEstimatedHalfDays(*v)
	}
	return _u
}

// AddEstimatedHalfDays adds value to the "estimated_half_days" field.
func (_u *DemandUpdateOne) AddEstimatedHalfDays(v int) *DemandUpdateOne {
	_u.mutation.AddEstimatedHalfDays(v)
	return _u
}

// SetEstimateConfirmedAt sets the "estimate_confirmed_at" field.
func (_u *DemandUpdateOne) SetEstimateConfirmedAt(v time.Time) *DemandUpdateOne {
	_u.mutation.SetEstimateConfirmedAt(v)
	return _u
}

// SetNillableEstimateConfirmedAt sets the "estimate_confirmed_at" field if the given value is not nil.
func (_u *DemandUpdateOne) SetNillableEstimateConfirmedAt(v *time.Time) *DemandUpdateOne {
	if v != nil {
		_u.SetEstimateConfirmedAt(*v)
	}
	return _u
}

// ClearEstimateConfirmedAt clears the value of the "estimate_confirmed_at" field.
func (_u *DemandUpdateOne) ClearEstimateConfirmedAt() *DemandUpdateOne {
	_u.mutation.ClearEstimateConfirmedAt()
	return _u
}

// SetEstimateConfirmedBy sets the "estimate_confirmed_by" field.
func (_u *DemandUpdateOne) SetEstimateConfirmedBy(v int) *DemandUpdateOne {
	_u.mutation.ResetEstimateConfirmedBy()
	_u.mutation.SetEstimateConfirmedBy(v)
	return _u
}

// SetNillableEstimateConfirmedBy sets the "estimate_confirmed_by" field if the given value is not nil.
func (_u *DemandUpdateOne) SetNillableEstimateConfirmedBy(v *int) *DemandUpdateOne {
	if v != nil {
		_u.SetEstimateConfirmedBy(*v)
	}
	return _u
}

// AddEstimateConfirmedBy adds value to the "estimate_confirmed_by" field.
func (_u *DemandUpdateOne) AddEstimateConfirmedBy(v int) *DemandUpdateOne {
	_u.mutation.AddEstimateConfirmedBy(v)
	return _u
}

// ClearEstimateConfirmedBy clears the value of the "estimate_confirmed_by" field.
func (_u *DemandUpdateOne) ClearEstimateConfirmedBy() *DemandUpdateOne {
	_u.mutation.ClearEstimateConfirmedBy()
	return _u
}

// SetPlannedStartDate sets the "planned_start_date" field.
func (_u *DemandUpdateOne) SetPlannedStartDate(v time.Time) *DemandUpdateOne {
	_u.mutation.SetPlannedStartDate(v)
	return _u
}

// SetNillablePlannedStartDate sets the "planned_start_date" field if the given value is not nil.
func (_u *DemandUpdateOne) SetNillablePlannedStartDate(v *time.Time) *DemandUpdateOne {
	if v != nil {
		_u.SetPlannedStartDate(*v)
	}
	return _u
}

// ClearPlannedStartDate clears the value of the "planned_start_date" field.
func (_u *DemandUpdateOne) ClearPlannedStartDate() *DemandUpdateOne {
	_u.mutation.ClearPlannedStartDate()
	return _u
}

// SetActualStartDate sets the "actual_start_date" field.
func (_u *DemandUpdateOne) SetActualStartDate(v time.Time) *DemandUpdateOne {
	_u.mutation.SetActualStartDate(v)
	return _u
}

// SetNillableActualStartDate sets the "actual_start_date" field if the given value is not nil.
func (_u *DemandUpdateOne) SetNillableActualStartDate(v *time.Time) *DemandUpdateOne {
	if v != nil {
		_u.SetActualStartDate(*v)
	}
	return _u
}

// ClearActualStartDate clears the value of the "actual_start_date" field.
func (_u *DemandUpdateOne) ClearActualStartDate() *DemandUpdateOne {
	_u.mutation.ClearActualStartDate()
	return _u
}

// SetActualEndDate sets the "actual_end_date" field.
func (_u *DemandUpdateOne) SetActualEndDate(v time.Time) *DemandUpdateOne {
	_u.mutation.SetActualEndDate(v)
	return _u
}

// SetNillableActualEndDate sets the "actual_end_date" field if the given value is not nil.
func (_u *DemandUpdateOne) SetNillableActualEndDate(v *time.Time) *DemandUpdateOne {
	if v != nil {
		_u.SetActualEndDate(*v)
	}
	return _u
}

// ClearActualEndDate clears the value of the "actual_end_date" field.
func (_u *DemandUpdateOne) ClearActualEndDate() *DemandUpdateOne {
	_u.mutation.ClearActualEndDate()
	return _u
}

// SetActualHalfDays sets the "actual_half_days" field.
func (_u *DemandUpdateOne) SetActualHalfDays(v int) *DemandUpdateOne {
	_u.mutation.ResetActualHalfDays()
	_u.mutation.SetActualHalfDays(v)
	return _u
}

// SetNillableActualHalfDays sets the "actual_half_days" field if the given value is not nil.
func (_u *DemandUpdateOne) SetNillableActualHalfDays(v *int) *DemandUpdateOne {
	if v != nil {
		_u.SetActualHalfDays(*v)
	}
	return _u
}

// AddActualHalfDays adds value to the "actual_half_days" field.
func (_u *DemandUpdateOne) AddActualHalfDays(v int) *DemandUpdateOne {
	_u.mutation.AddActualHalfDays(v)
	return _u
}

// ClearActualHalfDays clears the value of the "actual_half_days" field.
func (_u *DemandUpdateOne) ClearActualHalfDays() *DemandUpdateOne {
	_u.mutation.ClearActualHalfDays()
	return _u
}

// SetStatus sets the "status" field.
func (_u *DemandUpdateOne) SetStatus(v demand.Status) *DemandUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DemandUpdateOne) SetNillableStatus(v *demand.Status) *DemandUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAcceptDeadline sets the "accept_deadline" field.
func (_u *DemandUpdateOne) SetAcceptDeadline(v time.Time) *DemandUpdateOne {
	_u.mutation.SetAcceptDeadline(v)
	return _u
}

// SetNillableAcceptDeadline sets the "accept_deadline" field if the given value is not nil.
func (_u *DemandUpdateOne) SetNillableAcceptDeadline(v *time.Time) *DemandUpdateOne {
	if v != nil {
		_u.SetAcceptDeadline(*v)
	}
	return _u
}

// ClearAcceptDeadline clears the value of the "accept_deadline" field.
func (_u *DemandUpdateOne) ClearAcceptDeadline() *DemandUpdateOne {
	_u.mutation.ClearAcceptDeadline()
	return _u
}

// SetAcceptedAt sets the "accepted_at" field.
func (_u *DemandUpdateOne) SetAcceptedAt(v time.Time) *DemandUpdateOne {
	_u.mutation.SetAcceptedAt(v)
	return _u
}

// SetNillableAcceptedAt sets the "accepted_at" field if the given value is not nil.
func (_u *DemandUpdateOne) SetNillableAcceptedAt(v *time.Time) *DemandUpdateOne {
	if v != nil {
		_u.SetAcceptedAt(*v)
	}
	return _u
}

// ClearAcceptedAt clears the value of the "accepted_at" field.
func (_u *DemandUpdateOne) ClearAcceptedAt() *DemandUpdateOne {
	_u.mutation.ClearAcceptedAt()
	return _u
}

// SetAcceptedBy sets the "accepted_by" field.
func (_u *DemandUpdateOne) SetAcceptedBy(v int) *DemandUpdateOne {
	_u.mutation.ResetAcceptedBy()
	_u.mutation.SetAcceptedBy(v)
	return _u
}

// SetNillableAcceptedBy sets the "accepted_by" field if the given value is not nil.
func (_u *DemandUpdateOne) SetNillableAcceptedBy(v *int) *DemandUpdateOne {
	if v != nil {
		_u.SetAcceptedBy(*v)
	}
	return _u
}

// AddAcceptedBy adds value to the "accepted_by" field.
func (_u *DemandUpdateOne) AddAcceptedBy(v int) *DemandUpdateOne {
	_u.mutation.AddAcceptedBy(v)
	return _u
}

// ClearAcceptedBy clears the value of the "accepted_by" field.
func (_u *DemandUpdateOne) ClearAcceptedBy() *DemandUpdateOne {
	_u.mutation.ClearAcceptedBy()
	return _u
}

// SetAcceptAuto sets the "accept_auto" field.
func (_u *DemandUpdateOne) SetAcceptAuto(v bool) *DemandUpdateOne {
	_u.mutation.SetAcceptAuto(v)
	return _u
}

// SetNillableAcceptAuto sets the "accept_auto" field if the given value is not nil.
func (_u *DemandUpdateOne) SetNillableAcceptAuto(v *bool) *DemandUpdateOne {
	if v != nil {
		_u.SetAcceptAuto(*v)
	}
	return _u
}

// SetAcceptLocked sets the "accept_locked" field.
func (_u *DemandUpdateOne) SetAcceptLocked(v bool) *DemandUpdateOne {
	_u.mutation.SetAcceptLocked(v)
	return _u
}

// SetNillableAcceptLocked sets the "accept_locked" field if the given value is not nil.
func (_u *DemandUpdateOne) SetNillableAcceptLocked(v *bool) *DemandUpdateOne {
	if v != nil {
		_u.SetAcceptLocked(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DemandUpdateOne) SetUpdatedAt(v time.Time) *DemandUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddProjectIDs adds the "projects" edge to the Project entity by IDs.
func (_u *DemandUpdateOne) AddProjectIDs(ids ...int) *DemandUpdateOne {
	_u.mutation.AddProjectIDs(ids...)
	return _u
}

// AddProjects adds the "projects" edges to the Project entity.
func (_u *DemandUpdateOne) AddProjects(v ...*Project) *DemandUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProjectIDs(ids...)
}

// Mutation returns the DemandMutation object of the builder.
func (_u *DemandUpdateOne) Mutation() *DemandMutation {
	return _u.mutation
}

// ClearProjects clears all "projects" edges to the Project entity.
func (_u *DemandUpdateOne) ClearProjects() *DemandUpdateOne {
	_u.mutation.ClearProjects()
	return _u
}

// RemoveProjectIDs removes the "projects" edge to Project entities by IDs.
func (_u *DemandUpdateOne) RemoveProjectIDs(ids ...int) *DemandUpdateOne {
	_u.mutation.RemoveProjectIDs(ids...)
	return _u
}

// RemoveProjects removes "projects" edges to Project entities.
func (_u *DemandUpdateOne) RemoveProjects(v ...*Project) *DemandUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProjectIDs(ids...)
}

// Where appends a list predicates to the DemandUpdate builder.
func (_u *DemandUpdateOne) Where(ps ...predicate.Demand) *DemandUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DemandUpdateOne) Select(field string, fields ...string) *DemandUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Demand entity.
func (_u *DemandUpdateOne) Save(ctx context.Context) (*Demand, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DemandUpdateOne) SaveX(ctx context.Context) *Demand {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DemandUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DemandUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DemandUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if demand.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized demand.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := demand.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *DemandUpdateOne) check() error {
	if v, ok := _u.mutation.EstimatedHalfDays(); ok {
		if err := demand.EstimatedHalfDaysValidator(v); err != nil {
			return &ValidationError{Name: "estimated_half_days", err: fmt.Errorf(`ent: validator failed for field "Demand.estimated_half_days": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := demand.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Demand.status": %w`, err)}
		}
	}
	return nil
}

func (_u *DemandUpdateOne) sqlSave(ctx context.Context) (_node *Demand, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(demand.Table, demand.Columns, sqlgraph.NewFieldSpec(demand.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Demand.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, demand.FieldID)
		for _, f := range fields {
			if !demand.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != demand.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(demand.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(demand.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(demand.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(demand.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(demand.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.EstimatedHalfDays(); ok {
		_spec.SetField(demand.FieldEstimatedHalfDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEstimatedHalfDays(); ok {
		_spec.AddField(demand.FieldEstimatedHalfDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EstimateConfirmedAt(); ok {
		_spec.SetField(demand.FieldEstimateConfirmedAt, field.TypeTime, value)
	}
	if _u.mutation.EstimateConfirmedAtCleared() {
		_spec.ClearField(demand.FieldEstimateConfirmedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EstimateConfirmedBy(); ok {
		_spec.SetField(demand.FieldEstimateConfirmedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEstimateConfirmedBy(); ok {
		_spec.AddField(demand.FieldEstimateConfirmedBy, field.TypeInt, value)
	}
	if _u.mutation.EstimateConfirmedByCleared() {
		_spec.ClearField(demand.FieldEstimateConfirmedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.PlannedStartDate(); ok {
		_spec.SetField(demand.FieldPlannedStartDate, field.TypeTime, value)
	}
	if _u.mutation.PlannedStartDateCleared() {
		_spec.ClearField(demand.FieldPlannedStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.ActualStartDate(); ok {
		_spec.SetField(demand.FieldActualStartDate, field.TypeTime, value)
	}
	if _u.mutation.ActualStartDateCleared() {
		_spec.ClearField(demand.FieldActualStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.ActualEndDate(); ok {
		_spec.SetField(demand.FieldActualEndDate, field.TypeTime, value)
	}
	if _u.mutation.ActualEndDateCleared() {
		_spec.ClearField(demand.FieldActualEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.ActualHalfDays(); ok {
		_spec.SetField(demand.FieldActualHalfDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActualHalfDays(); ok {
		_spec.AddField(demand.FieldActualHalfDays, field.TypeInt, value)
	}
	if _u.mutation.ActualHalfDaysCleared() {
		_spec.ClearField(demand.FieldActualHalfDays, field.TypeInt)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(demand.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AcceptDeadline(); ok {
		_spec.SetField(demand.FieldAcceptDeadline, field.TypeTime, value)
	}
	if _u.mutation.AcceptDeadlineCleared() {
		_spec.ClearField(demand.FieldAcceptDeadline, field.TypeTime)
	}
	if value, ok := _u.mutation.AcceptedAt(); ok {
		_spec.SetField(demand.FieldAcceptedAt, field.TypeTime, value)
	}
	if _u.mutation.AcceptedAtCleared() {
		_spec.ClearField(demand.FieldAcceptedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AcceptedBy(); ok {
		_spec.SetField(demand.FieldAcceptedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAcceptedBy(); ok {
		_spec.AddField(demand.FieldAcceptedBy, field.TypeInt, value)
	}
	if _u.mutation.AcceptedByCleared() {
		_spec.ClearField(demand.FieldAcceptedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.AcceptAuto(); ok {
		_spec.SetField(demand.FieldAcceptAuto, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AcceptLocked(); ok {
		_spec.SetField(demand.FieldAcceptLocked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(demand.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   demand.ProjectsTable,
			Columns: demand.ProjectsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProjectsIDs(); len(nodes) > 0 && !_u.mutation.ProjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   demand.ProjectsTable,
			Columns: demand.ProjectsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   demand.ProjectsTable,
			Columns: demand.ProjectsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Demand{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{demand.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
