// Code generated by ent, DO NOT EDIT.

package ent

import (
	"clepsydra/internal/ent/holiday"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Holiday is the model entity for the Holiday schema.
type Holiday struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Date holds the value of the "date" field.
	Date string `json:"date,omitempty"`
	// Type holds the value of the "type" field.
	Type holiday.Type `json:"type,omitempty"`
	// Name holds the value of the "name" field.
	Name         string `json:"name,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Holiday) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case holiday.FieldID:
			values[i] = new(sql.NullInt64)
		case holiday.FieldDate, holiday.FieldType, holiday.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Holiday fields.
func (_m *Holiday) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case holiday.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case holiday.FieldDate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field date", values[i])
			} else if value.Valid {
				_m.Date = value.String
			}
		case holiday.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = holiday.Type(value.String)
			}
		case holiday.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Holiday.
// This includes values selected through modifiers, order, etc.
func (_m *Holiday) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Holiday.
// Note that you need to call Holiday.Unwrap() before calling this method if this Holiday
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Holiday) Update() *HolidayUpdateOne {
	return NewHolidayClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Holiday entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Holiday) Unwrap() *Holiday {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Holiday is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Holiday) String() string {
	var builder strings.Builder
	builder.WriteString("Holiday(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("date=")
	builder.WriteString(_m.Date)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Holidays is a parsable slice of Holiday.
type Holidays []*Holiday
