// Code generated by ent, DO NOT EDIT.

package ent

import (
	"clepsydra/internal/ent/holiday"
	"clepsydra/internal/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HolidayUpdate is the builder for updating Holiday entities.
type HolidayUpdate struct {
	config
	hooks    []Hook
	mutation *HolidayMutation
}

// Where appends a list predicates to the HolidayUpdate builder.
func (_u *HolidayUpdate) Where(ps ...predicate.Holiday) *HolidayUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDate sets the "date" field.
func (_u *HolidayUpdate) SetDate(v string) *HolidayUpdate {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *HolidayUpdate) SetNillableDate(v *string) *HolidayUpdate {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *HolidayUpdate) SetType(v holiday.Type) *HolidayUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *HolidayUpdate) SetNillableType(v *holiday.Type) *HolidayUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *HolidayUpdate) SetName(v string) *HolidayUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *HolidayUpdate) SetNillableName(v *string) *HolidayUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *HolidayUpdate) ClearName() *HolidayUpdate {
	_u.mutation.ClearName()
	return _u
}

// Mutation returns the HolidayMutation object of the builder.
func (_u *HolidayUpdate) Mutation() *HolidayMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HolidayUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HolidayUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HolidayUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HolidayUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HolidayUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := holiday.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Holiday.type": %w`, err)}
		}
	}
	return nil
}

func (_u *HolidayUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(holiday.Table, holiday.Columns, sqlgraph.NewFieldSpec(holiday.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(holiday.FieldDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(holiday.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(holiday.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(holiday.FieldName, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{holiday.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HolidayUpdateOne is the builder for updating a single Holiday entity.
type HolidayUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HolidayMutation
}

// SetDate sets the "date" field.
func (_u *HolidayUpdateOne) SetDate(v string) *HolidayUpdateOne {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *HolidayUpdateOne) SetNillableDate(v *string) *HolidayUpdateOne {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *HolidayUpdateOne) SetType(v holiday.Type) *HolidayUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *HolidayUpdateOne) SetNillableType(v *holiday.Type) *HolidayUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *HolidayUpdateOne) SetName(v string) *HolidayUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *HolidayUpdateOne) SetNillableName(v *string) *HolidayUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *HolidayUpdateOne) ClearName() *HolidayUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// Mutation returns the HolidayMutation object of the builder.
func (_u *HolidayUpdateOne) Mutation() *HolidayMutation {
	return _u.mutation
}

// Where appends a list predicates to the HolidayUpdate builder.
func (_u *HolidayUpdateOne) Where(ps ...predicate.Holiday) *HolidayUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HolidayUpdateOne) Select(field string, fields ...string) *HolidayUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Holiday entity.
func (_u *HolidayUpdateOne) Save(ctx context.Context) (*Holiday, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HolidayUpdateOne) SaveX(ctx context.Context) *Holiday {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HolidayUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HolidayUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HolidayUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := holiday.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Holiday.type": %w`, err)}
		}
	}
	return nil
}

func (_u *HolidayUpdateOne) sqlSave(ctx context.Context) (_node *Holiday, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(holiday.Table, holiday.Columns, sqlgraph.NewFieldSpec(holiday.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Holiday.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, holiday.FieldID)
		for _, f := range fields {
			if !holiday.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != holiday.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(holiday.FieldDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(holiday.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(holiday.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(holiday.FieldName, field.TypeString)
	}
	_node = &Holiday{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{holiday.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
