// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuditLog is the predicate function for auditlog builders.
type AuditLog func(*sql.Selector)

// Bill is the predicate function for bill builders.
type Bill func(*sql.Selector)

// BillItem is the predicate function for billitem builders.
type BillItem func(*sql.Selector)

// Demand is the predicate function for demand builders.
type Demand func(*sql.Selector)

// Holiday is the predicate function for holiday builders.
type Holiday func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
