// Code generated by ent, DO NOT EDIT.

package demand

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the demand type in the database.
	Label = "demand"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldEstimatedHalfDays holds the string denoting the estimated_half_days field in the database.
	FieldEstimatedHalfDays = "estimated_half_days"
	// FieldEstimateConfirmedAt holds the string denoting the estimate_confirmed_at field in the database.
	FieldEstimateConfirmedAt = "estimate_confirmed_at"
	// FieldEstimateConfirmedBy holds the string denoting the estimate_confirmed_by field in the database.
	FieldEstimateConfirmedBy = "estimate_confirmed_by"
	// FieldPlannedStartDate holds the string denoting the planned_start_date field in the database.
	FieldPlannedStartDate = "planned_start_date"
	// FieldActualStartDate holds the string denoting the actual_start_date field in the database.
	FieldActualStartDate = "actual_start_date"
	// FieldActualEndDate holds the string denoting the actual_end_date field in the database.
	FieldActualEndDate = "actual_end_date"
	// FieldActualHalfDays holds the string denoting the actual_half_days field in the database.
	FieldActualHalfDays = "actual_half_days"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldAcceptDeadline holds the string denoting the accept_deadline field in the database.
	FieldAcceptDeadline = "accept_deadline"
	// FieldAcceptedAt holds the string denoting the accepted_at field in the database.
	FieldAcceptedAt = "accepted_at"
	// FieldAcceptedBy holds the string denoting the accepted_by field in the database.
	FieldAcceptedBy = "accepted_by"
	// FieldAcceptAuto holds the string denoting the accept_auto field in the database.
	FieldAcceptAuto = "accept_auto"
	// FieldAcceptLocked holds the string denoting the accept_locked field in the database.
	FieldAcceptLocked = "accept_locked"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeProjects holds the string denoting the projects edge name in mutations.
	EdgeProjects = "projects"
	// EdgeTags holds the string denoting the tags edge name in mutations.
	EdgeTags = "tags"
	// Table holds the table name of the demand in the database.
	Table = "demands"
	// ProjectsTable is the table that holds the projects relation/edge. The primary key declared below.
	ProjectsTable = "project_demands"
	// ProjectsInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectsInverseTable = "projects"
	// TagsTable is the table that holds the tags relation/edge. The primary key declared below.
	TagsTable = "tag_demands"
	// TagsInverseTable is the table name for the Tag entity.
	// It exists in this package in order to avoid circular dependency with the "tag" package.
	TagsInverseTable = "tags"
)

// Columns holds all SQL columns for demand fields.
var Columns = []string{
	FieldID,
	FieldDeletedAt,
	FieldTitle,
	FieldDescription,
	FieldEstimatedHalfDays,
	FieldEstimateConfirmedAt,
	FieldEstimateConfirmedBy,
	FieldPlannedStartDate,
	FieldActualStartDate,
	FieldActualEndDate,
	FieldActualHalfDays,
	FieldStatus,
	FieldAcceptDeadline,
	FieldAcceptedAt,
	FieldAcceptedBy,
	FieldAcceptAuto,
	FieldAcceptLocked,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// ProjectsPrimaryKey and ProjectsColumn2 are the table columns denoting the
	// primary key for the projects relation (M2M).
	ProjectsPrimaryKey = []string{"project_id", "demand_id"}
	// TagsPrimaryKey and TagsColumn2 are the table columns denoting the
	// primary key for the tags relation (M2M).
	TagsPrimaryKey = []string{"tag_id", "demand_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "clepsydra/internal/ent/runtime"
var (
	Hooks        [2]ent.Hook
	Interceptors [1]ent.Interceptor
	// EstimatedHalfDaysValidator is a validator for the "estimated_half_days" field. It is called by the builders before save.
	EstimatedHalfDaysValidator func(int) error
	// DefaultAcceptAuto holds the default value on creation for the "accept_auto" field.
	DefaultAcceptAuto bool
	// DefaultAcceptLocked holds the default value on creation for the "accept_locked" field.
	DefaultAcceptLocked bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusDraft is the default value of the Status enum.
const DefaultStatus = StatusDraft

// Status values.
const (
	StatusDraft             Status = "draft"
	StatusPendingEstimate   Status = "pending_estimate"
	StatusConfirmed         Status = "confirmed"
	StatusInProgress        Status = "in_progress"
	StatusPendingAcceptance Status = "pending_acceptance"
	StatusAccepted          Status = "accepted"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusDraft, StatusPendingEstimate, StatusConfirmed, StatusInProgress, StatusPendingAcceptance, StatusAccepted:
		return nil
	default:
		return fmt.Errorf("demand: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Demand queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByEstimatedHalfDays orders the results by the estimated_half_days field.
func ByEstimatedHalfDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEstimatedHalfDays, opts...).ToFunc()
}

// ByEstimateConfirmedAt orders the results by the estimate_confirmed_at field.
func ByEstimateConfirmedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEstimateConfirmedAt, opts...).ToFunc()
}

// ByEstimateConfirmedBy orders the results by the estimate_confirmed_by field.
func ByEstimateConfirmedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEstimateConfirmedBy, opts...).ToFunc()
}

// ByPlannedStartDate orders the results by the planned_start_date field.
func ByPlannedStartDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlannedStartDate, opts...).ToFunc()
}

// ByActualStartDate orders the results by the actual_start_date field.
func ByActualStartDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualStartDate, opts...).ToFunc()
}

// ByActualEndDate orders the results by the actual_end_date field.
func ByActualEndDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualEndDate, opts...).ToFunc()
}

// ByActualHalfDays orders the results by the actual_half_days field.
func ByActualHalfDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualHalfDays, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAcceptDeadline orders the results by the accept_deadline field.
func ByAcceptDeadline(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAcceptDeadline, opts...).ToFunc()
}

// ByAcceptedAt orders the results by the accepted_at field.
func ByAcceptedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAcceptedAt, opts...).ToFunc()
}

// ByAcceptedBy orders the results by the accepted_by field.
func ByAcceptedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAcceptedBy, opts...).ToFunc()
}

// ByAcceptAuto orders the results by the accept_auto field.
func ByAcceptAuto(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAcceptAuto, opts...).ToFunc()
}

// ByAcceptLocked orders the results by the accept_locked field.
func ByAcceptLocked(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAcceptLocked, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByProjectsCount orders the results by projects count.
func ByProjectsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProjectsStep(), opts...)
	}
}

// ByProjects orders the results by projects terms.
func ByProjects(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTagsCount orders the results by tags count.
func ByTagsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTagsStep(), opts...)
	}
}

// ByTags orders the results by tags terms.
func ByTags(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTagsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newProjectsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, ProjectsTable, ProjectsPrimaryKey...),
	)
}
func newTagsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TagsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, TagsTable, TagsPrimaryKey...),
	)
}
