// Code generated by ent, DO NOT EDIT.

package demand

import (
	"clepsydra/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Demand {
	return predicate.Demand(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Demand {
	return predicate.Demand(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Demand {
	return predicate.Demand(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Demand {
	return predicate.Demand(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Demand {
	return predicate.Demand(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Demand {
	return predicate.Demand(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Demand {
	return predicate.Demand(sql.FieldLTE(FieldID, id))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldDeletedAt, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldDescription, v))
}

// EstimatedHalfDays applies equality check predicate on the "estimated_half_days" field. It's identical to EstimatedHalfDaysEQ.
func EstimatedHalfDays(v int) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldEstimatedHalfDays, v))
}

// EstimateConfirmedAt applies equality check predicate on the "estimate_confirmed_at" field. It's identical to EstimateConfirmedAtEQ.
func EstimateConfirmedAt(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldEstimateConfirmedAt, v))
}

// EstimateConfirmedBy applies equality check predicate on the "estimate_confirmed_by" field. It's identical to EstimateConfirmedByEQ.
func EstimateConfirmedBy(v int) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldEstimateConfirmedBy, v))
}

// PlannedStartDate applies equality check predicate on the "planned_start_date" field. It's identical to PlannedStartDateEQ.
func PlannedStartDate(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldPlannedStartDate, v))
}

// ActualStartDate applies equality check predicate on the "actual_start_date" field. It's identical to ActualStartDateEQ.
func ActualStartDate(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldActualStartDate, v))
}

// ActualEndDate applies equality check predicate on the "actual_end_date" field. It's identical to ActualEndDateEQ.
func ActualEndDate(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldActualEndDate, v))
}

// ActualHalfDays applies equality check predicate on the "actual_half_days" field. It's identical to ActualHalfDaysEQ.
func ActualHalfDays(v int) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldActualHalfDays, v))
}

// AcceptDeadline applies equality check predicate on the "accept_deadline" field. It's identical to AcceptDeadlineEQ.
func AcceptDeadline(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldAcceptDeadline, v))
}

// AcceptedAt applies equality check predicate on the "accepted_at" field. It's identical to AcceptedAtEQ.
func AcceptedAt(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldAcceptedAt, v))
}

// AcceptedBy applies equality check predicate on the "accepted_by" field. It's identical to AcceptedByEQ.
func AcceptedBy(v int) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldAcceptedBy, v))
}

// AcceptAuto applies equality check predicate on the "accept_auto" field. It's identical to AcceptAutoEQ.
func AcceptAuto(v bool) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldAcceptAuto, v))
}

// AcceptLocked applies equality check predicate on the "accept_locked" field. It's identical to AcceptLockedEQ.
func AcceptLocked(v bool) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldAcceptLocked, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Demand {
	return predicate.Demand(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Demand {
	return predicate.Demand(sql.FieldNotNull(FieldDeletedAt))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Demand {
	return predicate.Demand(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Demand {
	return predicate.Demand(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Demand {
	return predicate.Demand(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Demand {
	return predicate.Demand(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Demand {
	return predicate.Demand(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Demand {
	return predicate.Demand(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Demand {
	return predicate.Demand(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Demand {
	return predicate.Demand(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Demand {
	return predicate.Demand(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Demand {
	return predicate.Demand(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Demand {
	return predicate.Demand(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Demand {
	return predicate.Demand(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Demand {
	return predicate.Demand(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Demand {
	return predicate.Demand(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Demand {
	return predicate.Demand(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Demand {
	return predicate.Demand(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Demand {
	return predicate.Demand(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Demand {
	return predicate.Demand(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Demand {
	return predicate.Demand(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Demand {
	return predicate.Demand(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Demand {
	return predicate.Demand(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Demand {
	return predicate.Demand(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Demand {
	return predicate.Demand(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Demand {
	return predicate.Demand(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Demand {
	return predicate.Demand(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Demand {
	return predicate.Demand(sql.FieldContainsFold(FieldDescription, v))
}

// EstimatedHalfDaysEQ applies the EQ predicate on the "estimated_half_days" field.
func EstimatedHalfDaysEQ(v int) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldEstimatedHalfDays, v))
}

// EstimatedHalfDaysNEQ applies the NEQ predicate on the "estimated_half_days" field.
func EstimatedHalfDaysNEQ(v int) predicate.Demand {
	return predicate.Demand(sql.FieldNEQ(FieldEstimatedHalfDays, v))
}

// EstimatedHalfDaysIn applies the In predicate on the "estimated_half_days" field.
func EstimatedHalfDaysIn(vs ...int) predicate.Demand {
	return predicate.Demand(sql.FieldIn(FieldEstimatedHalfDays, vs...))
}

// EstimatedHalfDaysNotIn applies the NotIn predicate on the "estimated_half_days" field.
func EstimatedHalfDaysNotIn(vs ...int) predicate.Demand {
	return predicate.Demand(sql.FieldNotIn(FieldEstimatedHalfDays, vs...))
}

// EstimatedHalfDaysGT applies the GT predicate on the "estimated_half_days" field.
func EstimatedHalfDaysGT(v int) predicate.Demand {
	return predicate.Demand(sql.FieldGT(FieldEstimatedHalfDays, v))
}

// EstimatedHalfDaysGTE applies the GTE predicate on the "estimated_half_days" field.
func EstimatedHalfDaysGTE(v int) predicate.Demand {
	return predicate.Demand(sql.FieldGTE(FieldEstimatedHalfDays, v))
}

// EstimatedHalfDaysLT applies the LT predicate on the "estimated_half_days" field.
func EstimatedHalfDaysLT(v int) predicate.Demand {
	return predicate.Demand(sql.FieldLT(FieldEstimatedHalfDays, v))
}

// EstimatedHalfDaysLTE applies the LTE predicate on the "estimated_half_days" field.
func EstimatedHalfDaysLTE(v int) predicate.Demand {
	return predicate.Demand(sql.FieldLTE(FieldEstimatedHalfDays, v))
}

// EstimateConfirmedAtEQ applies the EQ predicate on the "estimate_confirmed_at" field.
func EstimateConfirmedAtEQ(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldEstimateConfirmedAt, v))
}

// EstimateConfirmedAtNEQ applies the NEQ predicate on the "estimate_confirmed_at" field.
func EstimateConfirmedAtNEQ(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldNEQ(FieldEstimateConfirmedAt, v))
}

// EstimateConfirmedAtIn applies the In predicate on the "estimate_confirmed_at" field.
func EstimateConfirmedAtIn(vs ...time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldIn(FieldEstimateConfirmedAt, vs...))
}

// EstimateConfirmedAtNotIn applies the NotIn predicate on the "estimate_confirmed_at" field.
func EstimateConfirmedAtNotIn(vs ...time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldNotIn(FieldEstimateConfirmedAt, vs...))
}

// EstimateConfirmedAtGT applies the GT predicate on the "estimate_confirmed_at" field.
func EstimateConfirmedAtGT(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldGT(FieldEstimateConfirmedAt, v))
}

// EstimateConfirmedAtGTE applies the GTE predicate on the "estimate_confirmed_at" field.
func EstimateConfirmedAtGTE(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldGTE(FieldEstimateConfirmedAt, v))
}

// EstimateConfirmedAtLT applies the LT predicate on the "estimate_confirmed_at" field.
func EstimateConfirmedAtLT(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldLT(FieldEstimateConfirmedAt, v))
}

// EstimateConfirmedAtLTE applies the LTE predicate on the "estimate_confirmed_at" field.
func EstimateConfirmedAtLTE(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldLTE(FieldEstimateConfirmedAt, v))
}

// EstimateConfirmedAtIsNil applies the IsNil predicate on the "estimate_confirmed_at" field.
func EstimateConfirmedAtIsNil() predicate.Demand {
	return predicate.Demand(sql.FieldIsNull(FieldEstimateConfirmedAt))
}

// EstimateConfirmedAtNotNil applies the NotNil predicate on the "estimate_confirmed_at" field.
func EstimateConfirmedAtNotNil() predicate.Demand {
	return predicate.Demand(sql.FieldNotNull(FieldEstimateConfirmedAt))
}

// EstimateConfirmedByEQ applies the EQ predicate on the "estimate_confirmed_by" field.
func EstimateConfirmedByEQ(v int) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldEstimateConfirmedBy, v))
}

// EstimateConfirmedByNEQ applies the NEQ predicate on the "estimate_confirmed_by" field.
func EstimateConfirmedByNEQ(v int) predicate.Demand {
	return predicate.Demand(sql.FieldNEQ(FieldEstimateConfirmedBy, v))
}

// EstimateConfirmedByIn applies the In predicate on the "estimate_confirmed_by" field.
func EstimateConfirmedByIn(vs ...int) predicate.Demand {
	return predicate.Demand(sql.FieldIn(FieldEstimateConfirmedBy, vs...))
}

// EstimateConfirmedByNotIn applies the NotIn predicate on the "estimate_confirmed_by" field.
func EstimateConfirmedByNotIn(vs ...int) predicate.Demand {
	return predicate.Demand(sql.FieldNotIn(FieldEstimateConfirmedBy, vs...))
}

// EstimateConfirmedByGT applies the GT predicate on the "estimate_confirmed_by" field.
func EstimateConfirmedByGT(v int) predicate.Demand {
	return predicate.Demand(sql.FieldGT(FieldEstimateConfirmedBy, v))
}

// EstimateConfirmedByGTE applies the GTE predicate on the "estimate_confirmed_by" field.
func EstimateConfirmedByGTE(v int) predicate.Demand {
	return predicate.Demand(sql.FieldGTE(FieldEstimateConfirmedBy, v))
}

// EstimateConfirmedByLT applies the LT predicate on the "estimate_confirmed_by" field.
func EstimateConfirmedByLT(v int) predicate.Demand {
	return predicate.Demand(sql.FieldLT(FieldEstimateConfirmedBy, v))
}

// EstimateConfirmedByLTE applies the LTE predicate on the "estimate_confirmed_by" field.
func EstimateConfirmedByLTE(v int) predicate.Demand {
	return predicate.Demand(sql.FieldLTE(FieldEstimateConfirmedBy, v))
}

// EstimateConfirmedByIsNil applies the IsNil predicate on the "estimate_confirmed_by" field.
func EstimateConfirmedByIsNil() predicate.Demand {
	return predicate.Demand(sql.FieldIsNull(FieldEstimateConfirmedBy))
}

// EstimateConfirmedByNotNil applies the NotNil predicate on the "estimate_confirmed_by" field.
func EstimateConfirmedByNotNil() predicate.Demand {
	return predicate.Demand(sql.FieldNotNull(FieldEstimateConfirmedBy))
}

// PlannedStartDateEQ applies the EQ predicate on the "planned_start_date" field.
func PlannedStartDateEQ(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldPlannedStartDate, v))
}

// PlannedStartDateNEQ applies the NEQ predicate on the "planned_start_date" field.
func PlannedStartDateNEQ(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldNEQ(FieldPlannedStartDate, v))
}

// PlannedStartDateIn applies the In predicate on the "planned_start_date" field.
func PlannedStartDateIn(vs ...time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldIn(FieldPlannedStartDate, vs...))
}

// PlannedStartDateNotIn applies the NotIn predicate on the "planned_start_date" field.
func PlannedStartDateNotIn(vs ...time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldNotIn(FieldPlannedStartDate, vs...))
}

// PlannedStartDateGT applies the GT predicate on the "planned_start_date" field.
func PlannedStartDateGT(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldGT(FieldPlannedStartDate, v))
}

// PlannedStartDateGTE applies the GTE predicate on the "planned_start_date" field.
func PlannedStartDateGTE(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldGTE(FieldPlannedStartDate, v))
}

// PlannedStartDateLT applies the LT predicate on the "planned_start_date" field.
func PlannedStartDateLT(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldLT(FieldPlannedStartDate, v))
}

// PlannedStartDateLTE applies the LTE predicate on the "planned_start_date" field.
func PlannedStartDateLTE(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldLTE(FieldPlannedStartDate, v))
}

// PlannedStartDateIsNil applies the IsNil predicate on the "planned_start_date" field.
func PlannedStartDateIsNil() predicate.Demand {
	return predicate.Demand(sql.FieldIsNull(FieldPlannedStartDate))
}

// PlannedStartDateNotNil applies the NotNil predicate on the "planned_start_date" field.
func PlannedStartDateNotNil() predicate.Demand {
	return predicate.Demand(sql.FieldNotNull(FieldPlannedStartDate))
}

// ActualStartDateEQ applies the EQ predicate on the "actual_start_date" field.
func ActualStartDateEQ(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldActualStartDate, v))
}

// ActualStartDateNEQ applies the NEQ predicate on the "actual_start_date" field.
func ActualStartDateNEQ(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldNEQ(FieldActualStartDate, v))
}

// ActualStartDateIn applies the In predicate on the "actual_start_date" field.
func ActualStartDateIn(vs ...time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldIn(FieldActualStartDate, vs...))
}

// ActualStartDateNotIn applies the NotIn predicate on the "actual_start_date" field.
func ActualStartDateNotIn(vs ...time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldNotIn(FieldActualStartDate, vs...))
}

// ActualStartDateGT applies the GT predicate on the "actual_start_date" field.
func ActualStartDateGT(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldGT(FieldActualStartDate, v))
}

// ActualStartDateGTE applies the GTE predicate on the "actual_start_date" field.
func ActualStartDateGTE(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldGTE(FieldActualStartDate, v))
}

// ActualStartDateLT applies the LT predicate on the "actual_start_date" field.
func ActualStartDateLT(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldLT(FieldActualStartDate, v))
}

// ActualStartDateLTE applies the LTE predicate on the "actual_start_date" field.
func ActualStartDateLTE(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldLTE(FieldActualStartDate, v))
}

// ActualStartDateIsNil applies the IsNil predicate on the "actual_start_date" field.
func ActualStartDateIsNil() predicate.Demand {
	return predicate.Demand(sql.FieldIsNull(FieldActualStartDate))
}

// ActualStartDateNotNil applies the NotNil predicate on the "actual_start_date" field.
func ActualStartDateNotNil() predicate.Demand {
	return predicate.Demand(sql.FieldNotNull(FieldActualStartDate))
}

// ActualEndDateEQ applies the EQ predicate on the "actual_end_date" field.
func ActualEndDateEQ(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldActualEndDate, v))
}

// ActualEndDateNEQ applies the NEQ predicate on the "actual_end_date" field.
func ActualEndDateNEQ(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldNEQ(FieldActualEndDate, v))
}

// ActualEndDateIn applies the In predicate on the "actual_end_date" field.
func ActualEndDateIn(vs ...time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldIn(FieldActualEndDate, vs...))
}

// ActualEndDateNotIn applies the NotIn predicate on the "actual_end_date" field.
func ActualEndDateNotIn(vs ...time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldNotIn(FieldActualEndDate, vs...))
}

// ActualEndDateGT applies the GT predicate on the "actual_end_date" field.
func ActualEndDateGT(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldGT(FieldActualEndDate, v))
}

// ActualEndDateGTE applies the GTE predicate on the "actual_end_date" field.
func ActualEndDateGTE(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldGTE(FieldActualEndDate, v))
}

// ActualEndDateLT applies the LT predicate on the "actual_end_date" field.
func ActualEndDateLT(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldLT(FieldActualEndDate, v))
}

// ActualEndDateLTE applies the LTE predicate on the "actual_end_date" field.
func ActualEndDateLTE(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldLTE(FieldActualEndDate, v))
}

// ActualEndDateIsNil applies the IsNil predicate on the "actual_end_date" field.
func ActualEndDateIsNil() predicate.Demand {
	return predicate.Demand(sql.FieldIsNull(FieldActualEndDate))
}

// ActualEndDateNotNil applies the NotNil predicate on the "actual_end_date" field.
func ActualEndDateNotNil() predicate.Demand {
	return predicate.Demand(sql.FieldNotNull(FieldActualEndDate))
}

// ActualHalfDaysEQ applies the EQ predicate on the "actual_half_days" field.
func ActualHalfDaysEQ(v int) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldActualHalfDays, v))
}

// ActualHalfDaysNEQ applies the NEQ predicate on the "actual_half_days" field.
func ActualHalfDaysNEQ(v int) predicate.Demand {
	return predicate.Demand(sql.FieldNEQ(FieldActualHalfDays, v))
}

// ActualHalfDaysIn applies the In predicate on the "actual_half_days" field.
func ActualHalfDaysIn(vs ...int) predicate.Demand {
	return predicate.Demand(sql.FieldIn(FieldActualHalfDays, vs...))
}

// ActualHalfDaysNotIn applies the NotIn predicate on the "actual_half_days" field.
func ActualHalfDaysNotIn(vs ...int) predicate.Demand {
	return predicate.Demand(sql.FieldNotIn(FieldActualHalfDays, vs...))
}

// ActualHalfDaysGT applies the GT predicate on the "actual_half_days" field.
func ActualHalfDaysGT(v int) predicate.Demand {
	return predicate.Demand(sql.FieldGT(FieldActualHalfDays, v))
}

// ActualHalfDaysGTE applies the GTE predicate on the "actual_half_days" field.
func ActualHalfDaysGTE(v int) predicate.Demand {
	return predicate.Demand(sql.FieldGTE(FieldActualHalfDays, v))
}

// ActualHalfDaysLT applies the LT predicate on the "actual_half_days" field.
func ActualHalfDaysLT(v int) predicate.Demand {
	return predicate.Demand(sql.FieldLT(FieldActualHalfDays, v))
}

// ActualHalfDaysLTE applies the LTE predicate on the "actual_half_days" field.
func ActualHalfDaysLTE(v int) predicate.Demand {
	return predicate.Demand(sql.FieldLTE(FieldActualHalfDays, v))
}

// ActualHalfDaysIsNil applies the IsNil predicate on the "actual_half_days" field.
func ActualHalfDaysIsNil() predicate.Demand {
	return predicate.Demand(sql.FieldIsNull(FieldActualHalfDays))
}

// ActualHalfDaysNotNil applies the NotNil predicate on the "actual_half_days" field.
func ActualHalfDaysNotNil() predicate.Demand {
	return predicate.Demand(sql.FieldNotNull(FieldActualHalfDays))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Demand {
	return predicate.Demand(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Demand {
	return predicate.Demand(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Demand {
	return predicate.Demand(sql.FieldNotIn(FieldStatus, vs...))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v Priority) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v Priority) predicate.Demand {
	return predicate.Demand(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...Priority) predicate.Demand {
	return predicate.Demand(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...Priority) predicate.Demand {
	return predicate.Demand(sql.FieldNotIn(FieldPriority, vs...))
}

// AcceptDeadlineEQ applies the EQ predicate on the "accept_deadline" field.
func AcceptDeadlineEQ(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldAcceptDeadline, v))
}

// AcceptDeadlineNEQ applies the NEQ predicate on the "accept_deadline" field.
func AcceptDeadlineNEQ(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldNEQ(FieldAcceptDeadline, v))
}

// AcceptDeadlineIn applies the In predicate on the "accept_deadline" field.
func AcceptDeadlineIn(vs ...time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldIn(FieldAcceptDeadline, vs...))
}

// AcceptDeadlineNotIn applies the NotIn predicate on the "accept_deadline" field.
func AcceptDeadlineNotIn(vs ...time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldNotIn(FieldAcceptDeadline, vs...))
}

// AcceptDeadlineGT applies the GT predicate on the "accept_deadline" field.
func AcceptDeadlineGT(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldGT(FieldAcceptDeadline, v))
}

// AcceptDeadlineGTE applies the GTE predicate on the "accept_deadline" field.
func AcceptDeadlineGTE(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldGTE(FieldAcceptDeadline, v))
}

// AcceptDeadlineLT applies the LT predicate on the "accept_deadline" field.
func AcceptDeadlineLT(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldLT(FieldAcceptDeadline, v))
}

// AcceptDeadlineLTE applies the LTE predicate on the "accept_deadline" field.
func AcceptDeadlineLTE(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldLTE(FieldAcceptDeadline, v))
}

// AcceptDeadlineIsNil applies the IsNil predicate on the "accept_deadline" field.
func AcceptDeadlineIsNil() predicate.Demand {
	return predicate.Demand(sql.FieldIsNull(FieldAcceptDeadline))
}

// AcceptDeadlineNotNil applies the NotNil predicate on the "accept_deadline" field.
func AcceptDeadlineNotNil() predicate.Demand {
	return predicate.Demand(sql.FieldNotNull(FieldAcceptDeadline))
}

// AcceptedAtEQ applies the EQ predicate on the "accepted_at" field.
func AcceptedAtEQ(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldAcceptedAt, v))
}

// AcceptedAtNEQ applies the NEQ predicate on the "accepted_at" field.
func AcceptedAtNEQ(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldNEQ(FieldAcceptedAt, v))
}

// AcceptedAtIn applies the In predicate on the "accepted_at" field.
func AcceptedAtIn(vs ...time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldIn(FieldAcceptedAt, vs...))
}

// AcceptedAtNotIn applies the NotIn predicate on the "accepted_at" field.
func AcceptedAtNotIn(vs ...time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldNotIn(FieldAcceptedAt, vs...))
}

// AcceptedAtGT applies the GT predicate on the "accepted_at" field.
func AcceptedAtGT(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldGT(FieldAcceptedAt, v))
}

// AcceptedAtGTE applies the GTE predicate on the "accepted_at" field.
func AcceptedAtGTE(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldGTE(FieldAcceptedAt, v))
}

// AcceptedAtLT applies the LT predicate on the "accepted_at" field.
func AcceptedAtLT(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldLT(FieldAcceptedAt, v))
}

// AcceptedAtLTE applies the LTE predicate on the "accepted_at" field.
func AcceptedAtLTE(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldLTE(FieldAcceptedAt, v))
}

// AcceptedAtIsNil applies the IsNil predicate on the "accepted_at" field.
func AcceptedAtIsNil() predicate.Demand {
	return predicate.Demand(sql.FieldIsNull(FieldAcceptedAt))
}

// AcceptedAtNotNil applies the NotNil predicate on the "accepted_at" field.
func AcceptedAtNotNil() predicate.Demand {
	return predicate.Demand(sql.FieldNotNull(FieldAcceptedAt))
}

// AcceptedByEQ applies the EQ predicate on the "accepted_by" field.
func AcceptedByEQ(v int) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldAcceptedBy, v))
}

// AcceptedByNEQ applies the NEQ predicate on the "accepted_by" field.
func AcceptedByNEQ(v int) predicate.Demand {
	return predicate.Demand(sql.FieldNEQ(FieldAcceptedBy, v))
}

// AcceptedByIn applies the In predicate on the "accepted_by" field.
func AcceptedByIn(vs ...int) predicate.Demand {
	return predicate.Demand(sql.FieldIn(FieldAcceptedBy, vs...))
}

// AcceptedByNotIn applies the NotIn predicate on the "accepted_by" field.
func AcceptedByNotIn(vs ...int) predicate.Demand {
	return predicate.Demand(sql.FieldNotIn(FieldAcceptedBy, vs...))
}

// AcceptedByGT applies the GT predicate on the "accepted_by" field.
func AcceptedByGT(v int) predicate.Demand {
	return predicate.Demand(sql.FieldGT(FieldAcceptedBy, v))
}

// AcceptedByGTE applies the GTE predicate on the "accepted_by" field.
func AcceptedByGTE(v int) predicate.Demand {
	return predicate.Demand(sql.FieldGTE(FieldAcceptedBy, v))
}

// AcceptedByLT applies the LT predicate on the "accepted_by" field.
func AcceptedByLT(v int) predicate.Demand {
	return predicate.Demand(sql.FieldLT(FieldAcceptedBy, v))
}

// AcceptedByLTE applies the LTE predicate on the "accepted_by" field.
func AcceptedByLTE(v int) predicate.Demand {
	return predicate.Demand(sql.FieldLTE(FieldAcceptedBy, v))
}

// AcceptedByIsNil applies the IsNil predicate on the "accepted_by" field.
func AcceptedByIsNil() predicate.Demand {
	return predicate.Demand(sql.FieldIsNull(FieldAcceptedBy))
}

// AcceptedByNotNil applies the NotNil predicate on the "accepted_by" field.
func AcceptedByNotNil() predicate.Demand {
	return predicate.Demand(sql.FieldNotNull(FieldAcceptedBy))
}

// AcceptAutoEQ applies the EQ predicate on the "accept_auto" field.
func AcceptAutoEQ(v bool) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldAcceptAuto, v))
}

// AcceptAutoNEQ applies the NEQ predicate on the "accept_auto" field.
func AcceptAutoNEQ(v bool) predicate.Demand {
	return predicate.Demand(sql.FieldNEQ(FieldAcceptAuto, v))
}

// AcceptLockedEQ applies the EQ predicate on the "accept_locked" field.
func AcceptLockedEQ(v bool) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldAcceptLocked, v))
}

// AcceptLockedNEQ applies the NEQ predicate on the "accept_locked" field.
func AcceptLockedNEQ(v bool) predicate.Demand {
	return predicate.Demand(sql.FieldNEQ(FieldAcceptLocked, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Demand {
	return predicate.Demand(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasProjects applies the HasEdge predicate on the "projects" edge.
func HasProjects() predicate.Demand {
	return predicate.Demand(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, ProjectsTable, ProjectsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectsWith applies the HasEdge predicate on the "projects" edge with a given conditions (other predicates).
func HasProjectsWith(preds ...predicate.Project) predicate.Demand {
	return predicate.Demand(func(s *sql.Selector) {
		step := newProjectsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTags applies the HasEdge predicate on the "tags" edge.
func HasTags() predicate.Demand {
	return predicate.Demand(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, TagsTable, TagsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTagsWith applies the HasEdge predicate on the "tags" edge with a given conditions (other predicates).
func HasTagsWith(preds ...predicate.Tag) predicate.Demand {
	return predicate.Demand(func(s *sql.Selector) {
		step := newTagsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Demand) predicate.Demand {
	return predicate.Demand(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Demand) predicate.Demand {
	return predicate.Demand(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Demand) predicate.Demand {
	return predicate.Demand(sql.NotPredicates(p))
}
