// Code generated by ent, DO NOT EDIT.

package billitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the billitem type in the database.
	Label = "bill_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDemandID holds the string denoting the demand_id field in the database.
	FieldDemandID = "demand_id"
	// FieldDemandTitle holds the string denoting the demand_title field in the database.
	FieldDemandTitle = "demand_title"
	// FieldDemandStatus holds the string denoting the demand_status field in the database.
	FieldDemandStatus = "demand_status"
	// FieldHalfDays holds the string denoting the half_days field in the database.
	FieldHalfDays = "half_days"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldBillable holds the string denoting the billable field in the database.
	FieldBillable = "billable"
	// FieldWaived holds the string denoting the waived field in the database.
	FieldWaived = "waived"
	// FieldPlannedStartDate holds the string denoting the planned_start_date field in the database.
	FieldPlannedStartDate = "planned_start_date"
	// FieldNote holds the string denoting the note field in the database.
	FieldNote = "note"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeBill holds the string denoting the bill edge name in mutations.
	EdgeBill = "bill"
	// Table holds the table name of the billitem in the database.
	Table = "bill_items"
	// BillTable is the table that holds the bill relation/edge.
	BillTable = "bill_items"
	// BillInverseTable is the table name for the Bill entity.
	// It exists in this package in order to avoid circular dependency with the "bill" package.
	BillInverseTable = "bills"
	// BillColumn is the table column denoting the bill relation/edge.
	BillColumn = "bill_items"
)

// Columns holds all SQL columns for billitem fields.
var Columns = []string{
	FieldID,
	FieldDemandID,
	FieldDemandTitle,
	FieldDemandStatus,
	FieldHalfDays,
	FieldAmount,
	FieldBillable,
	FieldWaived,
	FieldPlannedStartDate,
	FieldNote,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "bill_items"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"bill_items",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultWaived holds the default value on creation for the "waived" field.
	DefaultWaived bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the BillItem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDemandID orders the results by the demand_id field.
func ByDemandID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDemandID, opts...).ToFunc()
}

// ByDemandTitle orders the results by the demand_title field.
func ByDemandTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDemandTitle, opts...).ToFunc()
}

// ByDemandStatus orders the results by the demand_status field.
func ByDemandStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDemandStatus, opts...).ToFunc()
}

// ByHalfDays orders the results by the half_days field.
func ByHalfDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHalfDays, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByBillable orders the results by the billable field.
func ByBillable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillable, opts...).ToFunc()
}

// ByWaived orders the results by the waived field.
func ByWaived(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWaived, opts...).ToFunc()
}

// ByPlannedStartDate orders the results by the planned_start_date field.
func ByPlannedStartDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlannedStartDate, opts...).ToFunc()
}

// ByNote orders the results by the note field.
func ByNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNote, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByBillField orders the results by bill field.
func ByBillField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBillStep(), sql.OrderByField(field, opts...))
	}
}
func newBillStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BillInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, BillTable, BillColumn),
	)
}
