// Code generated by ent, DO NOT EDIT.

package billitem

import (
	"clepsydra/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.BillItem {
	return predicate.BillItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.BillItem {
	return predicate.BillItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.BillItem {
	return predicate.BillItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.BillItem {
	return predicate.BillItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.BillItem {
	return predicate.BillItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.BillItem {
	return predicate.BillItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.BillItem {
	return predicate.BillItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.BillItem {
	return predicate.BillItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.BillItem {
	return predicate.BillItem(sql.FieldLTE(FieldID, id))
}

// DemandID applies equality check predicate on the "demand_id" field. It's identical to DemandIDEQ.
func DemandID(v int) predicate.BillItem {
	return predicate.BillItem(sql.FieldEQ(FieldDemandID, v))
}

// DemandTitle applies equality check predicate on the "demand_title" field. It's identical to DemandTitleEQ.
func DemandTitle(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldEQ(FieldDemandTitle, v))
}

// DemandStatus applies equality check predicate on the "demand_status" field. It's identical to DemandStatusEQ.
func DemandStatus(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldEQ(FieldDemandStatus, v))
}

// HalfDays applies equality check predicate on the "half_days" field. It's identical to HalfDaysEQ.
func HalfDays(v int) predicate.BillItem {
	return predicate.BillItem(sql.FieldEQ(FieldHalfDays, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v int) predicate.BillItem {
	return predicate.BillItem(sql.FieldEQ(FieldAmount, v))
}

// Waived applies equality check predicate on the "waived" field. It's identical to WaivedEQ.
func Waived(v bool) predicate.BillItem {
	return predicate.BillItem(sql.FieldEQ(FieldWaived, v))
}

// PlannedStartDate applies equality check predicate on the "planned_start_date" field. It's identical to PlannedStartDateEQ.
func PlannedStartDate(v time.Time) predicate.BillItem {
	return predicate.BillItem(sql.FieldEQ(FieldPlannedStartDate, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldEQ(FieldNote, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BillItem {
	return predicate.BillItem(sql.FieldEQ(FieldCreatedAt, v))
}

// DemandIDEQ applies the EQ predicate on the "demand_id" field.
func DemandIDEQ(v int) predicate.BillItem {
	return predicate.BillItem(sql.FieldEQ(FieldDemandID, v))
}

// DemandIDNEQ applies the NEQ predicate on the "demand_id" field.
func DemandIDNEQ(v int) predicate.BillItem {
	return predicate.BillItem(sql.FieldNEQ(FieldDemandID, v))
}

// DemandIDIn applies the In predicate on the "demand_id" field.
func DemandIDIn(vs ...int) predicate.BillItem {
	return predicate.BillItem(sql.FieldIn(FieldDemandID, vs...))
}

// DemandIDNotIn applies the NotIn predicate on the "demand_id" field.
func DemandIDNotIn(vs ...int) predicate.BillItem {
	return predicate.BillItem(sql.FieldNotIn(FieldDemandID, vs...))
}

// DemandIDGT applies the GT predicate on the "demand_id" field.
func DemandIDGT(v int) predicate.BillItem {
	return predicate.BillItem(sql.FieldGT(FieldDemandID, v))
}

// DemandIDGTE applies the GTE predicate on the "demand_id" field.
func DemandIDGTE(v int) predicate.BillItem {
	return predicate.BillItem(sql.FieldGTE(FieldDemandID, v))
}

// DemandIDLT applies the LT predicate on the "demand_id" field.
func DemandIDLT(v int) predicate.BillItem {
	return predicate.BillItem(sql.FieldLT(FieldDemandID, v))
}

// DemandIDLTE applies the LTE predicate on the "demand_id" field.
func DemandIDLTE(v int) predicate.BillItem {
	return predicate.BillItem(sql.FieldLTE(FieldDemandID, v))
}

// DemandTitleEQ applies the EQ predicate on the "demand_title" field.
func DemandTitleEQ(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldEQ(FieldDemandTitle, v))
}

// DemandTitleNEQ applies the NEQ predicate on the "demand_title" field.
func DemandTitleNEQ(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldNEQ(FieldDemandTitle, v))
}

// DemandTitleIn applies the In predicate on the "demand_title" field.
func DemandTitleIn(vs ...string) predicate.BillItem {
	return predicate.BillItem(sql.FieldIn(FieldDemandTitle, vs...))
}

// DemandTitleNotIn applies the NotIn predicate on the "demand_title" field.
func DemandTitleNotIn(vs ...string) predicate.BillItem {
	return predicate.BillItem(sql.FieldNotIn(FieldDemandTitle, vs...))
}

// DemandTitleGT applies the GT predicate on the "demand_title" field.
func DemandTitleGT(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldGT(FieldDemandTitle, v))
}

// DemandTitleGTE applies the GTE predicate on the "demand_title" field.
func DemandTitleGTE(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldGTE(FieldDemandTitle, v))
}

// DemandTitleLT applies the LT predicate on the "demand_title" field.
func DemandTitleLT(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldLT(FieldDemandTitle, v))
}

// DemandTitleLTE applies the LTE predicate on the "demand_title" field.
func DemandTitleLTE(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldLTE(FieldDemandTitle, v))
}

// DemandTitleContains applies the Contains predicate on the "demand_title" field.
func DemandTitleContains(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldContains(FieldDemandTitle, v))
}

// DemandTitleHasPrefix applies the HasPrefix predicate on the "demand_title" field.
func DemandTitleHasPrefix(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldHasPrefix(FieldDemandTitle, v))
}

// DemandTitleHasSuffix applies the HasSuffix predicate on the "demand_title" field.
func DemandTitleHasSuffix(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldHasSuffix(FieldDemandTitle, v))
}

// DemandTitleEqualFold applies the EqualFold predicate on the "demand_title" field.
func DemandTitleEqualFold(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldEqualFold(FieldDemandTitle, v))
}

// DemandTitleContainsFold applies the ContainsFold predicate on the "demand_title" field.
func DemandTitleContainsFold(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldContainsFold(FieldDemandTitle, v))
}

// DemandStatusEQ applies the EQ predicate on the "demand_status" field.
func DemandStatusEQ(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldEQ(FieldDemandStatus, v))
}

// DemandStatusNEQ applies the NEQ predicate on the "demand_status" field.
func DemandStatusNEQ(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldNEQ(FieldDemandStatus, v))
}

// DemandStatusIn applies the In predicate on the "demand_status" field.
func DemandStatusIn(vs ...string) predicate.BillItem {
	return predicate.BillItem(sql.FieldIn(FieldDemandStatus, vs...))
}

// DemandStatusNotIn applies the NotIn predicate on the "demand_status" field.
func DemandStatusNotIn(vs ...string) predicate.BillItem {
	return predicate.BillItem(sql.FieldNotIn(FieldDemandStatus, vs...))
}

// DemandStatusGT applies the GT predicate on the "demand_status" field.
func DemandStatusGT(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldGT(FieldDemandStatus, v))
}

// DemandStatusGTE applies the GTE predicate on the "demand_status" field.
func DemandStatusGTE(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldGTE(FieldDemandStatus, v))
}

// DemandStatusLT applies the LT predicate on the "demand_status" field.
func DemandStatusLT(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldLT(FieldDemandStatus, v))
}

// DemandStatusLTE applies the LTE predicate on the "demand_status" field.
func DemandStatusLTE(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldLTE(FieldDemandStatus, v))
}

// DemandStatusContains applies the Contains predicate on the "demand_status" field.
func DemandStatusContains(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldContains(FieldDemandStatus, v))
}

// DemandStatusHasPrefix applies the HasPrefix predicate on the "demand_status" field.
func DemandStatusHasPrefix(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldHasPrefix(FieldDemandStatus, v))
}

// DemandStatusHasSuffix applies the HasSuffix predicate on the "demand_status" field.
func DemandStatusHasSuffix(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldHasSuffix(FieldDemandStatus, v))
}

// DemandStatusEqualFold applies the EqualFold predicate on the "demand_status" field.
func DemandStatusEqualFold(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldEqualFold(FieldDemandStatus, v))
}

// DemandStatusContainsFold applies the ContainsFold predicate on the "demand_status" field.
func DemandStatusContainsFold(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldContainsFold(FieldDemandStatus, v))
}

// HalfDaysEQ applies the EQ predicate on the "half_days" field.
func HalfDaysEQ(v int) predicate.BillItem {
	return predicate.BillItem(sql.FieldEQ(FieldHalfDays, v))
}

// HalfDaysNEQ applies the NEQ predicate on the "half_days" field.
func HalfDaysNEQ(v int) predicate.BillItem {
	return predicate.BillItem(sql.FieldNEQ(FieldHalfDays, v))
}

// HalfDaysIn applies the In predicate on the "half_days" field.
func HalfDaysIn(vs ...int) predicate.BillItem {
	return predicate.BillItem(sql.FieldIn(FieldHalfDays, vs...))
}

// HalfDaysNotIn applies the NotIn predicate on the "half_days" field.
func HalfDaysNotIn(vs ...int) predicate.BillItem {
	return predicate.BillItem(sql.FieldNotIn(FieldHalfDays, vs...))
}

// HalfDaysGT applies the GT predicate on the "half_days" field.
func HalfDaysGT(v int) predicate.BillItem {
	return predicate.BillItem(sql.FieldGT(FieldHalfDays, v))
}

// HalfDaysGTE applies the GTE predicate on the "half_days" field.
func HalfDaysGTE(v int) predicate.BillItem {
	return predicate.BillItem(sql.FieldGTE(FieldHalfDays, v))
}

// HalfDaysLT applies the LT predicate on the "half_days" field.
func HalfDaysLT(v int) predicate.BillItem {
	return predicate.BillItem(sql.FieldLT(FieldHalfDays, v))
}

// HalfDaysLTE applies the LTE predicate on the "half_days" field.
func HalfDaysLTE(v int) predicate.BillItem {
	return predicate.BillItem(sql.FieldLTE(FieldHalfDays, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v int) predicate.BillItem {
	return predicate.BillItem(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v int) predicate.BillItem {
	return predicate.BillItem(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...int) predicate.BillItem {
	return predicate.BillItem(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...int) predicate.BillItem {
	return predicate.BillItem(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v int) predicate.BillItem {
	return predicate.BillItem(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v int) predicate.BillItem {
	return predicate.BillItem(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v int) predicate.BillItem {
	return predicate.BillItem(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v int) predicate.BillItem {
	return predicate.BillItem(sql.FieldLTE(FieldAmount, v))
}

// WaivedEQ applies the EQ predicate on the "waived" field.
func WaivedEQ(v bool) predicate.BillItem {
	return predicate.BillItem(sql.FieldEQ(FieldWaived, v))
}

// WaivedNEQ applies the NEQ predicate on the "waived" field.
func WaivedNEQ(v bool) predicate.BillItem {
	return predicate.BillItem(sql.FieldNEQ(FieldWaived, v))
}

// PlannedStartDateEQ applies the EQ predicate on the "planned_start_date" field.
func PlannedStartDateEQ(v time.Time) predicate.BillItem {
	return predicate.BillItem(sql.FieldEQ(FieldPlannedStartDate, v))
}

// PlannedStartDateNEQ applies the NEQ predicate on the "planned_start_date" field.
func PlannedStartDateNEQ(v time.Time) predicate.BillItem {
	return predicate.BillItem(sql.FieldNEQ(FieldPlannedStartDate, v))
}

// PlannedStartDateIn applies the In predicate on the "planned_start_date" field.
func PlannedStartDateIn(vs ...time.Time) predicate.BillItem {
	return predicate.BillItem(sql.FieldIn(FieldPlannedStartDate, vs...))
}

// PlannedStartDateNotIn applies the NotIn predicate on the "planned_start_date" field.
func PlannedStartDateNotIn(vs ...time.Time) predicate.BillItem {
	return predicate.BillItem(sql.FieldNotIn(FieldPlannedStartDate, vs...))
}

// PlannedStartDateGT applies the GT predicate on the "planned_start_date" field.
func PlannedStartDateGT(v time.Time) predicate.BillItem {
	return predicate.BillItem(sql.FieldGT(FieldPlannedStartDate, v))
}

// PlannedStartDateGTE applies the GTE predicate on the "planned_start_date" field.
func PlannedStartDateGTE(v time.Time) predicate.BillItem {
	return predicate.BillItem(sql.FieldGTE(FieldPlannedStartDate, v))
}

// PlannedStartDateLT applies the LT predicate on the "planned_start_date" field.
func PlannedStartDateLT(v time.Time) predicate.BillItem {
	return predicate.BillItem(sql.FieldLT(FieldPlannedStartDate, v))
}

// PlannedStartDateLTE applies the LTE predicate on the "planned_start_date" field.
func PlannedStartDateLTE(v time.Time) predicate.BillItem {
	return predicate.BillItem(sql.FieldLTE(FieldPlannedStartDate, v))
}

// PlannedStartDateIsNil applies the IsNil predicate on the "planned_start_date" field.
func PlannedStartDateIsNil() predicate.BillItem {
	return predicate.BillItem(sql.FieldIsNull(FieldPlannedStartDate))
}

// PlannedStartDateNotNil applies the NotNil predicate on the "planned_start_date" field.
func PlannedStartDateNotNil() predicate.BillItem {
	return predicate.BillItem(sql.FieldNotNull(FieldPlannedStartDate))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.BillItem {
	return predicate.BillItem(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.BillItem {
	return predicate.BillItem(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.BillItem {
	return predicate.BillItem(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.BillItem {
	return predicate.BillItem(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.BillItem {
	return predicate.BillItem(sql.FieldContainsFold(FieldNote, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BillItem {
	return predicate.BillItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BillItem {
	return predicate.BillItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BillItem {
	return predicate.BillItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BillItem {
	return predicate.BillItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BillItem {
	return predicate.BillItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BillItem {
	return predicate.BillItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BillItem {
	return predicate.BillItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BillItem {
	return predicate.BillItem(sql.FieldLTE(FieldCreatedAt, v))
}

// HasBill applies the HasEdge predicate on the "bill" edge.
func HasBill() predicate.BillItem {
	return predicate.BillItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BillTable, BillColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBillWith applies the HasEdge predicate on the "bill" edge with a given conditions (other predicates).
func HasBillWith(preds ...predicate.Bill) predicate.BillItem {
	return predicate.BillItem(func(s *sql.Selector) {
		step := newBillStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BillItem) predicate.BillItem {
	return predicate.BillItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BillItem) predicate.BillItem {
	return predicate.BillItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BillItem) predicate.BillItem {
	return predicate.BillItem(sql.NotPredicates(p))
}
